In [2]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, StandardScaler
from utils import *
from valid_models import valid_models
from sklearn.model_selection import KFold

In [3]:
RANDOM_SEED = 1907
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

In [4]:
df=pd.read_csv("train.csv")
dfcopy = df.copy()
df

,carID,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
0,69512,VW,Golf,2016.0,22290,Semi-Auto,28421.0,Petrol,NaN,11.417268,2.0,63.0,4.000000,0.0
1,53000,Toyota,Yaris,2019.0,13790,Manual,4589.0,Petrol,145.0,47.900000,1.5,50.0,1.000000,0.0
2,6366,Audi,Q2,2019.0,24990,Semi-Auto,3624.0,Petrol,145.0,40.900000,1.5,56.0,4.000000,0.0
3,29021,Ford,FIESTA,2018.0,12500,anual,9102.0,Petrol,145.0,65.700000,1.0,50.0,-2.340306,0.0
4,10062,BMW,2 Series,2019.0,22995,Manual,1000.0,Petrol,145.0,42.800000,1.5,97.0,3.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75968,37194,Mercedes,C Class,2015.0,13498,Manual,14480.0,etrol,125.0,53.300000,2.0,78.0,0.000000,0.0
75969,6265,Audi,Q3,2013.0,12495,Semi-Auto,52134.0,Diesel,200.0,47.900000,2.0,38.0,2.000000,0.0
75970,54886,Toyota,Aygo,2017.0,8399,Automatic,11304.0,Petrol,145.0,67.000000,1.0,57.0,3.000000,0.0
75971,860,Audi,Q3,2015.0,12990,Manual,69072.0,iesel,125.0,60.100000,2.0,74.0,2.000000,0.0
75972,15795,Ford,Fiesta,2018.0,10495,Manual,16709.0,Petro,145.0,64.200000,1.1,38.0,1.000000,0.0

In [5]:
print(valid_models)

{'Audi': ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'T', 'R8', 'S3', 'S4', 'S5', 'S8', 'RS3', 'RS4', 'RS5', 'RS6', 'SQ5', 'SQ7'], 'Ford': ['FOCUS', 'FIESTA', 'MONDEO', 'KA', 'KA+', 'FUSION', 'KUGA', 'ECOSPORT', 'EDGE', 'PUMA', 'CMAX', 'BMAX', 'SMAX', 'GALAXY', 'GRANDCMAX', 'TOURNEOCONNECT', 'GRANDTOURNEOCONNECT', 'TOURNEOCUSTOM', 'MUSTANG', 'RANGER', 'ESCORT', 'STREETKA'], 'Mercedes': ['ACLASS', 'BCLASS', 'CCLASS', 'ECLASS', 'SCLASS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'GCLASS', 'GLCLASS', 'MCLASS', 'CLA', 'CLS', 'SL', 'SLK', 'CLK', 'VCLASS', 'XCLASS', 'CLC'], 'VW': ['GOLF', 'POLO', 'PASSAT', 'JETTA', 'ARTEON', 'SCIROCCO', 'BEETLE', 'UP', 'GOL', 'FOX', 'TIGUAN', 'TIGUANALLSPACE', 'TROC', 'TCROSS', 'TOUAREG', 'TOURAN', 'SHARAN', 'CADDY', 'CADDYMAXI', 'CADDYMAXILIFE', 'CARAVELLE', 'CALIFORNIA', 'SHUTTLE', 'AMAROK', 'GOLFSV', 'CC'], 'Opel': ['CORSA', 'ASTRA', 'INSIGNIA', 'VECTRA', 'MOKKA', 'MOKKAX', 'CROSSLAND', 'CROSSLANDX', 'GRANDLAND', 'GRANDLANDX', 'ANTARA', 'ZAFIRA', 'ZAFIRATOURER', 'MERIVA', 'COMBOLIFE', 'VIVARO', 'ADAM', 'AGILA', 'VIVA', 'TIGRA', 'GTC', 'CASCADA', 'AMPERA'], 'BMW': ['1SERIES', '2SERIES', '3SERIES', '4SERIES', '5SERIES', '6SERIES', '7SERIES', '8SERIES', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'M2', 'M3', 'M4', 'M5', 'M6', 'Z3', 'Z4', 'I3', 'I4', 'I8'], 'Toyota': ['YARIS', 'AYGO', 'AURIS', 'COROLLA', 'AVENSIS', 'CAMRY', 'PRIUS', 'CHR', 'RAV4', 'LANDCRUISER', 'URBANCRUISER', 'VERSO', 'VERSOS', 'PROACEVERSO', 'HILUX', 'GT86', 'SUPRA', 'IQ'], 'Skoda': ['FABIA', 'OCTAVIA', 'SUPERB', 'RAPID', 'SCALA', 'KODIAQ', 'KAROQ', 'KAMIQ', 'YETI', 'YETIOUTDOOR', 'CITIGO', 'ROOMSTER'], 'Hyundai': ['I10', 'I20', 'I30', 'I40', 'ACCENT', 'GETZ', 'KONA', 'TUCSON', 'SANTAFE', 'IX20', 'IX35', 'I800', 'IONIQ', 'VELOSTER', 'TERRACAN']}

In [6]:
num_cols = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
cat_cols = ['Brand', 'model', 'transmission']
int_cols = ['year']
float_cols = ['mileage', 'tax', 'mpg', 'engineSize']

drop_cols = ['paintQuality%', 'previousOwners', 'fuelType']

In [7]:
X=clean_df(df, valid_models, cat_cols)
X, y = separar_y(X)
X

,Brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners
carID,,,,,,,,,,,
69512,VW,GOLF,2016,SEMI-AUTO,28421.0,PETROL,NaN,11.417268,2.0,63.0,4
53000,Toyota,YARIS,2019,MANUAL,4589.0,PETROL,145.0,47.900000,1.5,50.0,1
6366,Audi,Q2,2019,SEMI-AUTO,3624.0,PETROL,145.0,40.900000,1.5,56.0,4
29021,Ford,FIESTA,2018,MANUAL,9102.0,PETROL,145.0,65.700000,1.0,50.0,<NA>
10062,BMW,2SERIES,2019,MANUAL,1000.0,PETROL,145.0,42.800000,1.5,97.0,3
...,...,...,...,...,...,...,...,...,...,...,...
37194,Mercedes,CCLASS,2015,MANUAL,14480.0,PETROL,125.0,53.300000,2.0,78.0,0
6265,Audi,Q3,2013,SEMI-AUTO,52134.0,DIESEL,200.0,47.900000,2.0,38.0,2
54886,Toyota,AYGO,2017,AUTOMATIC,11304.0,PETROL,145.0,67.000000,1.0,57.0,3
860,Audi,Q3,2015,MANUAL,69072.0,DIESEL,125.0,60.100000,2.0,74.0,2
15795,Ford,FIESTA,2018,MANUAL,16709.0,PETROL,145.0,64.200000,1.1,38.0,1

In [8]:
drop_cols = ['paintQuality%', 'previousOwners', 'fuelType']
X = X.drop(columns=drop_cols)
X

,Brand,model,year,transmission,mileage,tax,mpg,engineSize
carID,,,,,,,,
69512,VW,GOLF,2016,SEMI-AUTO,28421.0,NaN,11.417268,2.0
53000,Toyota,YARIS,2019,MANUAL,4589.0,145.0,47.900000,1.5
6366,Audi,Q2,2019,SEMI-AUTO,3624.0,145.0,40.900000,1.5
29021,Ford,FIESTA,2018,MANUAL,9102.0,145.0,65.700000,1.0
10062,BMW,2SERIES,2019,MANUAL,1000.0,145.0,42.800000,1.5
...,...,...,...,...,...,...,...,...
37194,Mercedes,CCLASS,2015,MANUAL,14480.0,125.0,53.300000,2.0
6265,Audi,Q3,2013,SEMI-AUTO,52134.0,200.0,47.900000,2.0
54886,Toyota,AYGO,2017,AUTOMATIC,11304.0,145.0,67.000000,1.0
860,Audi,Q3,2015,MANUAL,69072.0,125.0,60.100000,2.0
15795,Ford,FIESTA,2018,MANUAL,16709.0,145.0,64.200000,1.1

In [8]:
ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown="ignore")
scaler=None

In [9]:
"""results = random_search_cv(
    X, y,
    int_cols=int_cols,
    float_cols=float_cols,
    cat_cols=cat_cols,
    base_params={"random_state": 42, "n_jobs": -1},
    encoder=ohe,
    encoding_type="ohe",
    random_seed=RANDOM_SEED
)"""

'results = random_search_cv(\n    X, y,\n    int_cols=int_cols,\n    float_cols=float_cols,\n    cat_cols=cat_cols,\n    base_params={"random_state": 42, "n_jobs": -1},\n    encoder=ohe,\n    encoding_type="ohe",\n    random_seed=RANDOM_SEED\n)'

In [10]:
best_params = {'n_estimators': 150,
 'max_depth': 30,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 0.7,
 'max_samples': 0.8,
 'bootstrap': True}

In [11]:
rf_params = dict(random_state=RANDOM_SEED, n_jobs=-1, **best_params)
rf_model=RandomForestRegressor
final_model, fitted_scaler, fitted_encoder, fill_values, train_feature_cols, freq_values, outlier_info = run_model(
    X, y, int_cols, float_cols, model_class=rf_model, model_params=rf_params, scaler=None, encoder=ohe,
    cat_cols=cat_cols,
    encoding_type="ohe"
)

In [12]:
test_df = pd.read_csv("test.csv")
test_copy = test_df.copy()
X_test = clean_df(test_copy, valid_models, cat_cols)
X_test = X_test.drop(columns=drop_cols)
XcarID=X_test.copy()

In [13]:
y_pred = predict_test(
    X_test,
    model=final_model,
    int_cols=int_cols,
    float_cols=float_cols,
    fill_values=fill_values,
    scaler=fitted_scaler,
    encoder=fitted_encoder,
    cat_cols=cat_cols,
    train_feature_cols=train_feature_cols,
    freq_values=freq_values,
    encoding_type="ohe",
    outlier_info=outlier_info
)

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [14]:
submission = pd.DataFrame({
    "carID": XcarID.index,  
    "price": y_pred
})

# Check structure
display(submission.head())

# --- Save to CSV (with header, no index) ---
submission.to_csv("kaggle/model8.csv", index=False)

    carID         price
0   89856  12722.657385
1  106581  23907.149562
2   80886  14039.472022
3  100174  16608.387745
4   81376  25924.638489

In [15]:
ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown="ignore")
scaler = StandardScaler()
kf = KFold(n_splits=7, shuffle=True, random_state=RANDOM_SEED)
results = avg_score(
    method=kf,
    X=X,
    y=y,
    int_cols=int_cols,
    float_cols=float_cols,
    model_class=LinearRegression,
    model_params=None,
    scaler=scaler,
    encoder=ohe,
    cat_cols=cat_cols,
    encoding_type="ohe"
)

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

Average Train MAE: 2525.4264
Average Val MAE:   2536.8610
Average Train R²:  0.8260
Average Val R²:    0.8238

In [16]:
results

{'mae_train': [2518.596011756436,
  2527.970396088613,
  2527.495330402924,
  2539.387601492886,
  2526.736512579332,
  2516.572058550258,
  2521.226999463961],
 'mae_val': [2548.763982420558,
  2520.130727502965,
  2522.173561391569,
  2490.5450342463846,
  2531.281459545469,
  2569.8963377873292,
  2575.236122365992],
 'r2_train': [0.8267801683026821,
  0.8237969338349038,
  0.8249594528938337,
  0.8233969743265729,
  0.8264089163760523,
  0.8299721503379931,
  0.8266390377423644],
 'r2_val': [0.8183056737995036,
  0.8370480439944126,
  0.8303691868327807,
  0.8389186139285909,
  0.8215572239177997,
  0.8006585931926371,
  0.8200076182642819],
 'final_model': LinearRegression(),
 'fitted_scaler': StandardScaler(),
 'fitted_encoder': OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False),
 'fill_values': {'float': {'mileage': np.float64(23352.797091695324),
   'tax': np.float64(121.25927623394078),
   'mpg': np.float64(55.204844209618095),
   'engineSize': np.float64(1.6710558716569128)},
  'int': {'year': np.float64(2017.0)}},
 'train_feature_cols': ['year',
  'mileage',
  'tax',
  'mpg',
  'engineSize',
  'Brand_BMW',
  'Brand_Ford',
  'Brand_Hyundai',
  'Brand_Mercedes',
  'Brand_Opel',
  'Brand_Skoda',
  'Brand_Toyota',
  'Brand_UNKNOWN',
  'Brand_VW',
  'model_2SERIES',
  'model_3SERIES',
  'model_4SERIES',
  'model_5SERIES',
  'model_6SERIES',
  'model_7SERIES',
  'model_8SERIES',
  'model_A',
  'model_A1',
  'model_A2',
  'model_A3',
  'model_A4',
  'model_A5',
  'model_A6',
  'model_A7',
  'model_A8',
  'model_ACCENT',
  'model_ACLASS',
  'model_ADAM',
  'model_AGILA',
  'model_AMAROK',
  'model_AMPERA',
  'model_ANTARA',
  'model_ARTEON',
  'model_ASTR',
  'model_ASTRA',
  'model_AURIS',
  'model_AVENSIS',
  'model_AYGO',
  'model_BCLASS',
  'model_BEETLE',
  'model_BMAX',
  'model_CADDY',
  'model_CADDYMAXI',
  'model_CADDYMAXILIFE',
  'model_CALIFORNIA',
  'model_CAMRY',
  'model_CARAVELLE',
  'model_CASCADA',
  'model_CC',
  'model_CCLAS',
  'model_CCLASS',
  'model_CHR',
  'model_CITIGO',
  'model_CLCLAS',
  'model_CLCLASS',
  'model_CLK',
  'model_CLSCLASS',
  'model_CMAX',
  'model_COMBOLIFE',
  'model_COROLLA',
  'model_CORSA',
  'model_CROSSLAND',
  'model_CROSSLANDX',
  'model_ECLASS',
  'model_ECOSPORT',
  'model_EDGE',
  'model_ESCORT',
  'model_FABIA',
  'model_FIEST',
  'model_FIESTA',
  'model_FOCU',
  'model_FOCUS',
  'model_FOX',
  'model_FUSION',
  'model_GALAXY',
  'model_GCLASS',
  'model_GETZ',
  'model_GLACLAS',
  'model_GLACLASS',
  'model_GLBCLASS',
  'model_GLCCLASS',
  'model_GLCLASS',
  'model_GLECLASS',
  'model_GLSCLASS',
  'model_GOL',
  'model_GOLF',
  'model_GOLFSV',
  'model_GRANDCMA',
  'model_GRANDCMAX',
  'model_GRANDLAND',
  'model_GRANDLANDX',
  'model_GRANDTOURNEOCONNECT',
  'model_GT86',
  'model_GTC',
  'model_HILUX',
  'model_I10',
  'model_I20',
  'model_I3',
  'model_I30',
  'model_I40',
  'model_I8',
  'model_I800',
  'model_INSIGNIA',
  'model_IONIQ',
  'model_IQ',
  'model_IX20',
  'model_IX35',
  'model_JETTA',
  'model_KA',
  'model_KA+',
  'model_KAMIQ',
  'model_KARO',
  'model_KAROQ',
  'model_KODIAQ',
  'model_KONA',
  'model_KUGA',
  'model_LANDCRUISER',
  'model_M2',
  'model_M3',
  'model_M4',
  'model_M5',
  'model_M6',
  'model_MCLASS',
  'model_MERIVA',
  'model_MOKKA',
  'model_MOKKAX',
  'model_MONDEO',
  'model_MUSTANG',
  'model_OCTAVIA',
  'model_PASSAT',
  'model_POL',
  'model_POLO',
  'model_PRIUS',
  'model_PROACEVERSO',
  'model_PUMA',
  'model_Q',
  'model_Q2',
  'model_Q3',
  'model_Q5',
  'model_Q7',
  'model_Q8',
  'model_R8',
  'model_RANGER',
  'model_RAPID',
  'model_RAV4',
  'model_ROOMSTER',
  'model_RS3',
  'model_RS4',
  'model_RS5',
  'model_RS6',
  'model_S3',
  'model_S4',
  'model_S5',
  'model_S8',
  'model_SANTAFE',
  'model_SCAL',
  'model_SCALA',
  'model_SCIROCCO',
  'model_SCLASS',
  'model_SHARAN',
  'model_SHUTTLE',
  'model_SL',
  'model_SLCLASS',
  'model_SLK',
  'model_SMAX',
  'model_SQ5',
  'model_SQ7',
  'model_STREETKA',
  'model_SUPERB',
  'model_SUPRA',
  'model_T',
  'model_TCROSS',
  'model_TERRACAN',
  'model_TIGRA',
  'model_TIGUA',
  'model_TIGUAN',
  'model_TIGUANALLSPACE',
  'model_TOUAREG',
  'model_TOURAN',
  'model_TOURNEOCONNECT',
  'model_TOURNEOCUSTOM',
  'model_TROC',
  'model_TT',
  'model_TUCSON',
  'model_UNKNOWN',
  'model_UP',
  'model_URBANCRUISER',
  'model_VCLASS',
  'model_VECTRA',
  'model_VELOSTER',
  'model_VERSO',
  'model_VERSOS',
  'model_VIVA',
  'model_VIVARO',
  'model_X',
  'model_X1',
  'model_X2',
  'model_X3',
  'model_X4',
  'model_X5',
  'model_X6',
  'model_X7',
  'model_XCLASS',
  'model_YARI',
  'model_YARIS',
  'model_YETI',
  'model_YETIOUTDOO',
  'model_YETIOUTDOOR',
  'model_Z3',
  'model_Z4',
  'model_ZAFIRA',
  'model_ZAFIRATOURER',
  'transmission_MANUAL',
  'transmission_OTHER',
  'transmission_SEMI-AUTO',
  'transmission_UNKNOWN'],
 'freq_values': None,
 'outlier_info': {'mileage': {'log_transform': True},
  'tax': {'upper': np.float64(235.0)},
  'mpg': {'upper': np.float64(78.5)},
  'engineSize': {'lower': np.float64(1.0), 'upper': np.float64(3.0)}}}

In [17]:
model = results["final_model"]
scaler = results["fitted_scaler"]
encoder = results["fitted_encoder"]
fill_values = results["fill_values"]
train_feature_cols = results["train_feature_cols"]
outlier_info = results["outlier_info"]

In [18]:
test_df = pd.read_csv("test.csv")
test_copy = test_df.copy()
X_test = clean_df(test_copy, valid_models, cat_cols)
X_test = X_test.drop(columns=drop_cols)
XcarID=X_test.copy()

In [19]:
y_pred = predict_test(
    X_test,
    model=model,
    int_cols=int_cols,
    float_cols=float_cols,
    fill_values=fill_values,
    scaler=scaler,
    encoder=encoder,
    cat_cols=cat_cols,
    train_feature_cols=train_feature_cols,
    outlier_info=outlier_info
)

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [20]:
submission = pd.DataFrame({
    "carID": XcarID.index,  
    "price": y_pred
})

# Check structure
display(submission.head())

# --- Save to CSV (with header, no index) ---
submission.to_csv("kaggle/model9.csv", index=False)

    carID         price
0   89856  14603.730027
1  106581  23247.574965
2   80886  13634.655968
3  100174  18145.676545
4   81376  22643.098266

In [58]:
base_params = {
    "solver": "adam",
    "early_stopping": True,
    "random_state": RANDOM_SEED,
    "validation_fraction": 0.1,   # 10% of TRAIN fold used for internal ES
    "n_iter_no_change": 7,       # early stopping patience
}

In [ ]:
param_dist = {
    "hidden_layer_sizes": [
        (7,), (8,), (9,), (10,),
        
        (6, 4),
        (7, 5),
        (8, 6),
        (9, 5),
        (10, 6),

        (5, 3, 2),
        (6, 4, 2),
        (7, 5, 3),
        (8, 6, 4),
        (8, 5, 3),
        (9, 7, 5),
        (10, 8, 6),

        (10, 8, 6, 4),
        (9, 7, 5, 3),
        (8, 6, 4, 2),
        (7, 5, 3, 2),
    ],

    "activation": ["relu", "sigmoid", "tanh"],

    "learning_rate_init": [
        5e-4,
        1e-3,
        2e-3,
        3e-3,
        5e-3,
    ],

    "batch_size": [128, 256, 512],

    "alpha": [
        1e-4,
        3e-4,
        1e-3,
        3e-3,
        2e-3,
        5e-3,
        6e-3
        1e-2,
    ],
}

In [ ]:
scaler = MinMaxScaler()
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

results = random_search_cv(
    X, y,
    int_cols=int_cols,
    float_cols=float_cols,
    cat_cols=cat_cols,
    model_class=MLPRegressor,
    base_params=base_params,
    param_dist=param_dist,
    n_iter=300,
    method=None,
    scaler=scaler,
    encoder=encoder,
    encoding_type="ohe",
    random_seed=RANDOM_SEED,
)

Randomized Search with 7-Fold CV (MAE Optimization)
Testing 300 random parameter combinations

► Combination 1/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 6), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 256, 'alpha': 0.01}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2682.1871, Val MAE = 2672.2573, Train R² = 0.7925, Val R² = 0.8019

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2718.3310, Val MAE = 2703.4721, Train R² = 0.7852, Val R² = 0.7995

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 3575.2343, Val MAE = 3608.1732, Train R² = 0.6450, Val R² = 0.6484

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2769.2615, Val MAE = 2697.6214, Train R² = 0.7786, Val R² = 0.7973

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 3255.8040, Val MAE = 3263.2063, Train R² = 0.7040, Val R² = 0.6954
   Fold 6: Train MAE = 16881.9126, Val MAE = 16874.3745, Train R² = -3.0172, Val R² = -2.9384

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2665.4769, Val MAE = 2756.8702, Train R² = 0.7891, Val R² = 0.7603
→ Avg Train MAE: 4935.4582 | Avg Val MAE: 4939.4250 | Avg Train R²: 0.2110 | Avg Val R²: 0.2235

► Combination 2/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 256, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2306.4480, Val MAE = 2317.0895, Train R² = 0.8329, Val R² = 0.8406

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2334.5413, Val MAE = 2293.5525, Train R² = 0.8304, Val R² = 0.8447

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2660.3739, Val MAE = 2651.9354, Train R² = 0.7958, Val R² = 0.8006

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2340.6851, Val MAE = 2276.2708, Train R² = 0.8362, Val R² = 0.8522

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2644.0301, Val MAE = 2659.4719, Train R² = 0.8010, Val R² = 0.7923
   Fold 6: Train MAE = 16880.8616, Val MAE = 16873.3234, Train R² = -3.0169, Val R² = -2.9380

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2348.7130, Val MAE = 2437.4740, Train R² = 0.8334, Val R² = 0.8112
→ Avg Train MAE: 4502.2361 | Avg Val MAE: 4501.3025 | Avg Train R²: 0.2733 | Avg Val R²: 0.2862

► Combination 3/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 512, 'alpha': 0.001}
   Fold 1: Train MAE = 16886.5935, Val MAE = 16831.3040, Train R² = -2.9976, Val R² = -3.0506
   Fold 2: Train MAE = 16900.0883, Val MAE = 16750.3462, Train R² = -3.0111, Val R² = -2.9689
   Fold 3: Train MAE = 7003.5063, Val MAE = 7106.0079, Train R² = -0.0000, Val R² = -0.0001

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 11565.3603, Val MAE = 11594.5065, Train R² = -1.3899, Val R² = -1.4248
   Fold 5: Train MAE = 7006.5664, Val MAE = 6982.2814, Train R² = -0.0001, Val R² = -0.0006
   Fold 6: Train MAE = 16882.0103, Val MAE = 16874.4722, Train R² = -3.0173, Val R² = -2.9384
   Fold 7: Train MAE = 16875.9057, Val MAE = 16895.4254, Train R² = -3.0041, Val R² = -3.0104
→ Avg Train MAE: 13302.8616 | Avg Val MAE: 13290.6205 | Avg Train R²: -1.9171 | Avg Val R²: -1.9134

► Combination 4/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 128, 'alpha': 0.003}
   Fold 1: Train MAE = 16888.7257, Val MAE = 16833.4362, Train R² = -2.9983, Val R² = -3.0514
   Fold 2: Train MAE = 16902.2204, Val MAE = 16752.4783, Train R² = -3.0119, Val R² = -2.9697
   Fold 3: Train MAE = 16874.5097, Val MAE = 16911.3371, Train R² = -3.0107, Val R² = -2.9736
   Fold 4: Train MAE = 16876.7939, Val MAE = 16905.5727, Train R² = -2.9959, Val R² = -3.0663
   Fold 5: Train MAE = 16861.5630, Val MAE = 16989.0225, Train R² = -3.0007, Val R² = -3.0339
   Fold 6: Train MAE = 16882.1863, Val MAE = 16874.6482, Train R² = -3.0173, Val R² = -2.9385
   Fold 7: Train MAE = 16878.0394, Val MAE = 16897.5590, Train R² = -3.0048, Val R² = -3.0111
→ Avg Train MAE: 16880.5769 | Avg Val MAE: 16880.5792 | Avg Train R²: -3.0057 | Avg Val R²: -3.0064

► Combination 5/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 6), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 256, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2385.2118, Val MAE = 2388.2762, Train R² = 0.8327, Val R² = 0.8373

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2332.9974, Val MAE = 2298.8496, Train R² = 0.8355, Val R² = 0.8484

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2641.0411, Val MAE = 2635.1442, Train R² = 0.8008, Val R² = 0.8056

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2441.8192, Val MAE = 2392.5410, Train R² = 0.8268, Val R² = 0.8415

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2680.5220, Val MAE = 2695.2582, Train R² = 0.7954, Val R² = 0.7863
   Fold 6: Train MAE = 16880.8825, Val MAE = 16873.3443, Train R² = -3.0169, Val R² = -2.9380

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2017.3064, Val MAE = 2089.3727, Train R² = 0.8692, Val R² = 0.8541
→ Avg Train MAE: 4482.8258 | Avg Val MAE: 4481.8266 | Avg Train R²: 0.2777 | Avg Val R²: 0.2907

► Combination 6/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8,), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 128, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 4135.7058, Val MAE = 4118.7527, Train R² = 0.5390, Val R² = 0.5517

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 4129.7441, Val MAE = 4148.2994, Train R² = 0.5409, Val R² = 0.5476

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 5080.7743, Val MAE = 5147.0916, Train R² = 0.3854, Val R² = 0.3865

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 4156.0453, Val MAE = 4102.4075, Train R² = 0.5395, Val R² = 0.5531

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 4810.7012, Val MAE = 4779.4464, Train R² = 0.4249, Val R² = 0.4233

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 4125.8724, Val MAE = 4152.9893, Train R² = 0.5476, Val R² = 0.5312

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 4154.8397, Val MAE = 4191.3430, Train R² = 0.5400, Val R² = 0.5212
→ Avg Train MAE: 4370.5261 | Avg Val MAE: 4377.1900 | Avg Train R²: 0.5025 | Avg Val R²: 0.5021

► Combination 7/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 256, 'alpha': 0.001}
   Fold 1: Train MAE = 1897.5609, Val MAE = 1926.6157, Train R² = 0.8908, Val R² = 0.8892
   Fold 2: Train MAE = 1928.0222, Val MAE = 1928.5809, Train R² = 0.8868, Val R² = 0.8946
   Fold 3: Train MAE = 1880.0465, Val MAE = 1889.3119, Train R² = 0.8938, Val R² = 0.8910
   Fold 4: Train MAE = 1901.9700, Val MAE = 1884.3714, Train R² = 0.8895, Val R² = 0.8978

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1859.3601, Val MAE = 1888.1794, Train R² = 0.8965, Val R² = 0.8896
   Fold 6: Train MAE = 1885.2363, Val MAE = 1927.2396, Train R² = 0.8950, Val R² = 0.8703
   Fold 7: Train MAE = 1932.5512, Val MAE = 1973.1582, Train R² = 0.8869, Val R² = 0.8843
→ Avg Train MAE: 1897.8210 | Avg Val MAE: 1916.7796 | Avg Train R²: 0.8913 | Avg Val R²: 0.8881

► Combination 8/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 128, 'alpha': 0.0001}
   Fold 1: Train MAE = 1900.6988, Val MAE = 1920.5349, Train R² = 0.8919, Val R² = 0.8912
   Fold 2: Train MAE = 1882.7103, Val MAE = 1885.0030, Train R² = 0.8934, Val R² = 0.9003

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 15962.6638, Val MAE = 15999.5422, Train R² = -2.6941, Val R² = -2.6616

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 15964.4118, Val MAE = 15993.1477, Train R² = -2.6807, Val R² = -2.7443

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 15949.7565, Val MAE = 16077.1043, Train R² = -2.6849, Val R² = -2.7169

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 15969.2724, Val MAE = 15961.7123, Train R² = -2.6998, Val R² = -2.6291
   Fold 7: Train MAE = 1892.5440, Val MAE = 1930.0567, Train R² = 0.8923, Val R² = 0.8921
→ Avg Train MAE: 9931.7225 | Avg Val MAE: 9966.7287 | Avg Train R²: -1.1545 | Avg Val R²: -1.1526

► Combination 9/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 5), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 128, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2105.0267, Val MAE = 2130.1471, Train R² = 0.8642, Val R² = 0.8675

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2442.5415, Val MAE = 2414.6568, Train R² = 0.8315, Val R² = 0.8444

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2003.5713, Val MAE = 1996.9841, Train R² = 0.8717, Val R² = 0.8754

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2126.5602, Val MAE = 2076.0329, Train R² = 0.8621, Val R² = 0.8740

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1969.9145, Val MAE = 1988.8354, Train R² = 0.8780, Val R² = 0.8712

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2241.9211, Val MAE = 2303.8542, Train R² = 0.8582, Val R² = 0.8320

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2108.1133, Val MAE = 2180.5373, Train R² = 0.8652, Val R² = 0.8520
→ Avg Train MAE: 2142.5212 | Avg Val MAE: 2155.8640 | Avg Train R²: 0.8615 | Avg Val R²: 0.8595

► Combination 10/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 512, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1906.6287, Val MAE = 1940.6726, Train R² = 0.8875, Val R² = 0.8867

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1859.0381, Val MAE = 1846.8622, Train R² = 0.8916, Val R² = 0.9011

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1924.1696, Val MAE = 1926.4429, Train R² = 0.8879, Val R² = 0.8885

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1943.7500, Val MAE = 1916.5238, Train R² = 0.8854, Val R² = 0.8949

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1936.0924, Val MAE = 1949.6516, Train R² = 0.8847, Val R² = 0.8784

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1915.2463, Val MAE = 1958.8995, Train R² = 0.8901, Val R² = 0.8659

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1911.6945, Val MAE = 1946.6885, Train R² = 0.8885, Val R² = 0.8852
→ Avg Train MAE: 1913.8028 | Avg Val MAE: 1926.5345 | Avg Train R²: 0.8880 | Avg Val R²: 0.8858

► Combination 11/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9,), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 256, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 4166.3000, Val MAE = 4148.2407, Train R² = 0.5323, Val R² = 0.5447

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 4168.5809, Val MAE = 4188.6338, Train R² = 0.5326, Val R² = 0.5390

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 4029.7249, Val MAE = 4054.2990, Train R² = 0.5614, Val R² = 0.5653

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 3784.0444, Val MAE = 3719.1544, Train R² = 0.6052, Val R² = 0.6220

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 4037.3252, Val MAE = 4035.4128, Train R² = 0.5628, Val R² = 0.5566

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 3916.6809, Val MAE = 3942.1425, Train R² = 0.5844, Val R² = 0.5678

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 4202.3357, Val MAE = 4236.8321, Train R² = 0.5296, Val R² = 0.5113
→ Avg Train MAE: 4043.5703 | Avg Val MAE: 4046.3879 | Avg Train R²: 0.5583 | Avg Val R²: 0.5581

► Combination 12/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (6, 4), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 128, 'alpha': 0.001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2001.5121, Val MAE = 2027.5560, Train R² = 0.8775, Val R² = 0.8782

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16720.3289, Val MAE = 16570.5869, Train R² = -2.9474, Val R² = -2.9055

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1938.2977, Val MAE = 1940.4016, Train R² = 0.8866, Val R² = 0.8870

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 9727.4030, Val MAE = 9758.8642, Train R² = -0.9414, Val R² = -0.9661

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1931.0128, Val MAE = 1948.8422, Train R² = 0.8872, Val R² = 0.8804

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1899.5247, Val MAE = 1950.4633, Train R² = 0.8910, Val R² = 0.8689

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2034.5912, Val MAE = 2094.2314, Train R² = 0.8755, Val R² = 0.8675
→ Avg Train MAE: 5178.9529 | Avg Val MAE: 5184.4208 | Avg Train R²: 0.0756 | Avg Val R²: 0.0729

► Combination 13/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 5), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 512, 'alpha': 0.001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 3660.9300, Val MAE = 3656.0326, Train R² = 0.6303, Val R² = 0.6400

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 3709.5769, Val MAE = 3707.5146, Train R² = 0.6218, Val R² = 0.6320

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 3936.0241, Val MAE = 3967.9479, Train R² = 0.5809, Val R² = 0.5848

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 3895.6825, Val MAE = 3830.2872, Train R² = 0.5890, Val R² = 0.6059

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 3874.6022, Val MAE = 3879.7451, Train R² = 0.5954, Val R² = 0.5882

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 3294.4431, Val MAE = 3314.0390, Train R² = 0.6983, Val R² = 0.6810

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 3694.9389, Val MAE = 3746.3094, Train R² = 0.6286, Val R² = 0.6049
→ Avg Train MAE: 3723.7425 | Avg Val MAE: 3728.8394 | Avg Train R²: 0.6206 | Avg Val R²: 0.6196

► Combination 14/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (6, 4), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 256, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2054.0558, Val MAE = 2076.6391, Train R² = 0.8716, Val R² = 0.8739

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16811.7401, Val MAE = 16661.9981, Train R² = -2.9797, Val R² = -2.9377

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2031.6490, Val MAE = 2028.4607, Train R² = 0.8744, Val R² = 0.8775

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2055.2932, Val MAE = 2013.2895, Train R² = 0.8692, Val R² = 0.8800

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2024.8924, Val MAE = 2036.9277, Train R² = 0.8755, Val R² = 0.8692

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2057.4186, Val MAE = 2102.6304, Train R² = 0.8702, Val R² = 0.8468

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2059.6309, Val MAE = 2123.7921, Train R² = 0.8717, Val R² = 0.8617
→ Avg Train MAE: 4156.3828 | Avg Val MAE: 4149.1054 | Avg Train R²: 0.3218 | Avg Val R²: 0.3245

► Combination 15/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 512, 'alpha': 0.001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2256.5279, Val MAE = 2271.4088, Train R² = 0.8442, Val R² = 0.8493

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2265.6680, Val MAE = 2227.3993, Train R² = 0.8420, Val R² = 0.8559

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2550.3681, Val MAE = 2534.9920, Train R² = 0.8074, Val R² = 0.8127

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2216.4319, Val MAE = 2161.2453, Train R² = 0.8514, Val R² = 0.8649

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2523.7020, Val MAE = 2543.2450, Train R² = 0.8130, Val R² = 0.8044
   Fold 6: Train MAE = 16880.8567, Val MAE = 16873.3186, Train R² = -3.0169, Val R² = -2.9380

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2257.2164, Val MAE = 2336.9718, Train R² = 0.8459, Val R² = 0.8276
→ Avg Train MAE: 4421.5387 | Avg Val MAE: 4421.2258 | Avg Train R²: 0.2839 | Avg Val R²: 0.2967

► Combination 16/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 128, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 16433.5161, Val MAE = 16378.2278, Train R² = -2.8389, Val R² = -2.8886

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16447.0155, Val MAE = 16297.2732, Train R² = -2.8518, Val R² = -2.8105

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 16419.3154, Val MAE = 16456.1426, Train R² = -2.8505, Val R² = -2.8157

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 16421.5990, Val MAE = 16450.3777, Train R² = -2.8364, Val R² = -2.9034

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 16406.3664, Val MAE = 16533.8257, Train R² = -2.8408, Val R² = -2.8735

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16426.9874, Val MAE = 16419.4490, Train R² = -2.8568, Val R² = -2.7821

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 16422.8444, Val MAE = 16442.3638, Train R² = -2.8449, Val R² = -2.8511
→ Avg Train MAE: 16425.3777 | Avg Val MAE: 16425.3800 | Avg Train R²: -2.8457 | Avg Val R²: -2.8464

► Combination 17/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 128, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 16614.5009, Val MAE = 16559.2114, Train R² = -2.9017, Val R² = -2.9527

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16627.9997, Val MAE = 16478.2576, Train R² = -2.9149, Val R² = -2.8732
   Fold 3: Train MAE = 7006.9283, Val MAE = 7109.4246, Train R² = -0.0000, Val R² = -0.0000
   Fold 4: Train MAE = 7029.3297, Val MAE = 6982.0353, Train R² = -0.0000, Val R² = -0.0000
   Fold 5: Train MAE = 7014.7414, Val MAE = 6989.8008, Train R² = -0.0000, Val R² = -0.0004

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16609.6874, Val MAE = 16602.1493, Train R² = -2.9207, Val R² = -2.8444

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 16603.8130, Val MAE = 16623.3326, Train R² = -2.9080, Val R² = -2.9142
→ Avg Train MAE: 12501.0000 | Avg Val MAE: 12477.7445 | Avg Train R²: -1.6636 | Avg Val R²: -1.6550

► Combination 18/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 512, 'alpha': 0.0003}
   Fold 1: Train MAE = 2042.9895, Val MAE = 2087.4198, Train R² = 0.8824, Val R² = 0.8798

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2002.6776, Val MAE = 2010.0883, Train R² = 0.8841, Val R² = 0.8938
   Fold 3: Train MAE = 1904.7603, Val MAE = 1914.3272, Train R² = 0.8913, Val R² = 0.8892
   Fold 4: Train MAE = 2019.2922, Val MAE = 2003.9412, Train R² = 0.8838, Val R² = 0.8916
   Fold 5: Train MAE = 1938.3527, Val MAE = 1955.6156, Train R² = 0.8901, Val R² = 0.8829

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16652.0923, Val MAE = 16644.5542, Train R² = -2.9357, Val R² = -2.8589
   Fold 7: Train MAE = 2000.3656, Val MAE = 2037.6905, Train R² = 0.8858, Val R² = 0.8838
→ Avg Train MAE: 4080.0758 | Avg Val MAE: 4093.3767 | Avg Train R²: 0.3403 | Avg Val R²: 0.3517

► Combination 19/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 256, 'alpha': 0.01}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2642.8672, Val MAE = 2638.8842, Train R² = 0.8001, Val R² = 0.8078

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2706.1930, Val MAE = 2688.9948, Train R² = 0.7876, Val R² = 0.8023

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1909.3912, Val MAE = 1917.3285, Train R² = 0.8900, Val R² = 0.8889

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1824.0872, Val MAE = 1825.9645, Train R² = 0.8984, Val R² = 0.9041

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1894.4776, Val MAE = 1918.1871, Train R² = 0.8906, Val R² = 0.8838

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1875.5328, Val MAE = 1931.5436, Train R² = 0.8983, Val R² = 0.8754

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 16649.9520, Val MAE = 16669.4717, Train R² = -2.9242, Val R² = -2.9304
→ Avg Train MAE: 4214.6430 | Avg Val MAE: 4227.1963 | Avg Train R²: 0.3201 | Avg Val R²: 0.3188

► Combination 20/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 128, 'alpha': 0.001}
   Fold 1: Train MAE = 1872.1153, Val MAE = 1900.9743, Train R² = 0.8950, Val R² = 0.8935
   Fold 2: Train MAE = 1878.7079, Val MAE = 1886.6588, Train R² = 0.8924, Val R² = 0.8979
   Fold 3: Train MAE = 1873.5558, Val MAE = 1883.5125, Train R² = 0.8960, Val R² = 0.8914
   Fold 4: Train MAE = 7051.9769, Val MAE = 7002.8619, Train R² = -0.0001, Val R² = -0.0000
   Fold 5: Train MAE = 1865.6694, Val MAE = 1886.1313, Train R² = 0.8946, Val R² = 0.8880
   Fold 6: Train MAE = 1920.0797, Val MAE = 1967.3552, Train R² = 0.8935, Val R² = 0.8674
   Fold 7: Train MAE = 1891.5885, Val MAE = 1926.0695, Train R² = 0.8926, Val R² = 0.8922
→ Avg Train MAE: 2621.9562 | Avg Val MAE: 2636.2234 | Avg Train R²: 0.7663 | Avg Val R²: 0.7615

► Combination 21/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 128, 'alpha': 0.01}
   Fold 1: Train MAE = 1781.8325, Val MAE = 1821.8816, Train R² = 0.9026, Val R² = 0.9007
   Fold 2: Train MAE = 1892.4568, Val MAE = 1890.6036, Train R² = 0.8899, Val R² = 0.8990
   Fold 3: Train MAE = 1902.6860, Val MAE = 1911.0769, Train R² = 0.8899, Val R² = 0.8884
   Fold 4: Train MAE = 1771.3869, Val MAE = 1792.1895, Train R² = 0.9036, Val R² = 0.9075
   Fold 5: Train MAE = 1869.0642, Val MAE = 1895.3544, Train R² = 0.8928, Val R² = 0.8864
   Fold 6: Train MAE = 1890.4382, Val MAE = 1927.4626, Train R² = 0.8944, Val R² = 0.8701
   Fold 7: Train MAE = 1893.1331, Val MAE = 1941.2678, Train R² = 0.8915, Val R² = 0.8898
→ Avg Train MAE: 1857.2854 | Avg Val MAE: 1882.8338 | Avg Train R²: 0.8950 | Avg Val R²: 0.8917

► Combination 22/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 6), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 128, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2142.5510, Val MAE = 2180.9987, Train R² = 0.8647, Val R² = 0.8650

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2233.1879, Val MAE = 2205.2624, Train R² = 0.8528, Val R² = 0.8647

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2361.1400, Val MAE = 2355.1492, Train R² = 0.8348, Val R² = 0.8393

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2199.4124, Val MAE = 2162.1575, Train R² = 0.8552, Val R² = 0.8680

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2316.8091, Val MAE = 2326.7044, Train R² = 0.8399, Val R² = 0.8319

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 3406.3144, Val MAE = 3424.5432, Train R² = 0.6792, Val R² = 0.6630

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1888.3741, Val MAE = 1931.8514, Train R² = 0.8907, Val R² = 0.8840
→ Avg Train MAE: 2363.9698 | Avg Val MAE: 2369.5238 | Avg Train R²: 0.8310 | Avg Val R²: 0.8309

► Combination 23/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 6), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 512, 'alpha': 0.0003}
   Fold 1: Train MAE = 1905.7383, Val MAE = 1931.2910, Train R² = 0.8909, Val R² = 0.8902
   Fold 2: Train MAE = 1919.9182, Val MAE = 1924.5305, Train R² = 0.8879, Val R² = 0.8960

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1916.0699, Val MAE = 1923.2047, Train R² = 0.8885, Val R² = 0.8881
   Fold 4: Train MAE = 1896.6517, Val MAE = 1876.5011, Train R² = 0.8891, Val R² = 0.8976

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1925.9392, Val MAE = 1949.6853, Train R² = 0.8889, Val R² = 0.8817

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16653.1396, Val MAE = 16645.6014, Train R² = -2.9360, Val R² = -2.8593
   Fold 7: Train MAE = 1918.1297, Val MAE = 1950.6648, Train R² = 0.8898, Val R² = 0.8890
→ Avg Train MAE: 4019.3695 | Avg Val MAE: 4028.7827 | Avg Train R²: 0.3427 | Avg Val R²: 0.3548

► Combination 24/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7,), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 128, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2600.4011, Val MAE = 2599.4712, Train R² = 0.7989, Val R² = 0.8083

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2612.0874, Val MAE = 2592.5731, Train R² = 0.7967, Val R² = 0.8110

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2792.0600, Val MAE = 2800.6784, Train R² = 0.7724, Val R² = 0.7759

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2598.4183, Val MAE = 2524.2311, Train R² = 0.7993, Val R² = 0.8182

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2788.1054, Val MAE = 2798.6427, Train R² = 0.7750, Val R² = 0.7662

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2684.3724, Val MAE = 2730.5259, Train R² = 0.7952, Val R² = 0.7749

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2728.5309, Val MAE = 2821.7927, Train R² = 0.7867, Val R² = 0.7595
→ Avg Train MAE: 2686.2822 | Avg Val MAE: 2695.4164 | Avg Train R²: 0.7892 | Avg Val R²: 0.7877

► Combination 25/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 512, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1906.6287, Val MAE = 1940.6726, Train R² = 0.8875, Val R² = 0.8867

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1859.0381, Val MAE = 1846.8622, Train R² = 0.8916, Val R² = 0.9011

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1924.1696, Val MAE = 1926.4429, Train R² = 0.8879, Val R² = 0.8885

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1943.7500, Val MAE = 1916.5238, Train R² = 0.8854, Val R² = 0.8949

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1936.0924, Val MAE = 1949.6516, Train R² = 0.8847, Val R² = 0.8784

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1915.2463, Val MAE = 1958.8995, Train R² = 0.8901, Val R² = 0.8659

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1911.6945, Val MAE = 1946.6885, Train R² = 0.8885, Val R² = 0.8852
→ Avg Train MAE: 1913.8028 | Avg Val MAE: 1926.5345 | Avg Train R²: 0.8880 | Avg Val R²: 0.8858

► Combination 26/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (6, 4), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 128, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 16798.3031, Val MAE = 16743.0136, Train R² = -2.9663, Val R² = -3.0187

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16811.7948, Val MAE = 16662.0528, Train R² = -2.9797, Val R² = -2.9377

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2119.8604, Val MAE = 2116.4407, Train R² = 0.8627, Val R² = 0.8664

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 14375.7478, Val MAE = 14404.4419, Train R² = -2.1721, Val R² = -2.2246

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2069.5362, Val MAE = 2080.1248, Train R² = 0.8699, Val R² = 0.8636

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2324.3048, Val MAE = 2389.5712, Train R² = 0.8388, Val R² = 0.8143

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2241.8689, Val MAE = 2324.7241, Train R² = 0.8494, Val R² = 0.8313
→ Avg Train MAE: 8105.9166 | Avg Val MAE: 8102.9099 | Avg Train R²: -0.6710 | Avg Val R²: -0.6865

► Combination 27/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7,), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 256, 'alpha': 0.01}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2422.7684, Val MAE = 2428.9580, Train R² = 0.8243, Val R² = 0.8317

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2428.5303, Val MAE = 2393.0537, Train R² = 0.8230, Val R² = 0.8372

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2533.8872, Val MAE = 2520.3032, Train R² = 0.8081, Val R² = 0.8133

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2307.0638, Val MAE = 2242.5188, Train R² = 0.8350, Val R² = 0.8517

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2625.0954, Val MAE = 2639.8590, Train R² = 0.8043, Val R² = 0.7955

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2315.1756, Val MAE = 2384.7260, Train R² = 0.8397, Val R² = 0.8163

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2414.8943, Val MAE = 2502.5876, Train R² = 0.8279, Val R² = 0.8063
→ Avg Train MAE: 2435.3450 | Avg Val MAE: 2444.5723 | Avg Train R²: 0.8232 | Avg Val R²: 0.8217

► Combination 28/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 512, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2925.3428, Val MAE = 2921.3272, Train R² = 0.7536, Val R² = 0.7605

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2931.3161, Val MAE = 2922.0132, Train R² = 0.7513, Val R² = 0.7668

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 3177.1254, Val MAE = 3205.2311, Train R² = 0.7152, Val R² = 0.7186
   Fold 4: Train MAE = 16876.3944, Val MAE = 16905.1733, Train R² = -2.9957, Val R² = -3.0662

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 3183.2780, Val MAE = 3193.4489, Train R² = 0.7175, Val R² = 0.7089

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 3666.9042, Val MAE = 3690.4751, Train R² = 0.6363, Val R² = 0.6192

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2921.4769, Val MAE = 3012.2333, Train R² = 0.7582, Val R² = 0.7287
→ Avg Train MAE: 5097.4054 | Avg Val MAE: 5121.4146 | Avg Train R²: 0.1909 | Avg Val R²: 0.1767

► Combination 29/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 256, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2585.1946, Val MAE = 2607.3045, Train R² = 0.8342, Val R² = 0.8316

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2416.3949, Val MAE = 2438.3614, Train R² = 0.6763, Val R² = 0.6844

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2002.5814, Val MAE = 2007.7623, Train R² = 0.8832, Val R² = 0.8841

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1777.9165, Val MAE = 1793.2295, Train R² = 0.9018, Val R² = 0.9055

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1981.3767, Val MAE = 1991.9091, Train R² = 0.8839, Val R² = 0.8779
   Fold 6: Train MAE = 1879.9548, Val MAE = 1924.0676, Train R² = 0.8949, Val R² = 0.8706
   Fold 7: Train MAE = 7018.2924, Val MAE = 6964.8691, Train R² = -0.0001, Val R² = -0.0001
→ Avg Train MAE: 2808.8159 | Avg Val MAE: 2818.2148 | Avg Train R²: 0.7249 | Avg Val R²: 0.7220

► Combination 30/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 128, 'alpha': 0.01}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1936.1621, Val MAE = 1963.2012, Train R² = 0.8876, Val R² = 0.8871

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1930.4223, Val MAE = 1932.5233, Train R² = 0.8867, Val R² = 0.8955

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 16693.8305, Val MAE = 16730.6578, Train R² = -2.9466, Val R² = -2.9104

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 16695.5431, Val MAE = 16724.3220, Train R² = -2.9319, Val R² = -3.0009

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 16680.8866, Val MAE = 16808.3461, Train R² = -2.9367, Val R² = -2.9697

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16700.4372, Val MAE = 16692.8990, Train R² = -2.9527, Val R² = -2.8755

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1926.4122, Val MAE = 1959.9727, Train R² = 0.8883, Val R² = 0.8871
→ Avg Train MAE: 10366.2420 | Avg Val MAE: 10401.7032 | Avg Train R²: -1.3008 | Avg Val R²: -1.2981

► Combination 31/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10,), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 256, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 5856.0154, Val MAE = 5856.5246, Train R² = 0.1259, Val R² = 0.1319

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 5875.5610, Val MAE = 5882.8395, Train R² = 0.1240, Val R² = 0.1294

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 5223.9200, Val MAE = 5296.4318, Train R² = 0.3656, Val R² = 0.3662

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 6751.8977, Val MAE = 6767.4577, Train R² = -0.1706, Val R² = -0.1765

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 5068.4205, Val MAE = 5032.0956, Train R² = 0.3913, Val R² = 0.3904

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 5680.8027, Val MAE = 5645.7868, Train R² = 0.2521, Val R² = 0.2445

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 5919.6396, Val MAE = 5884.4013, Train R² = 0.1212, Val R² = 0.1174
→ Avg Train MAE: 5768.0367 | Avg Val MAE: 5766.5053 | Avg Train R²: 0.1728 | Avg Val R²: 0.1719

► Combination 32/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 128, 'alpha': 0.0001}
   Fold 1: Train MAE = 1868.9576, Val MAE = 1909.9706, Train R² = 0.8942, Val R² = 0.8922
   Fold 2: Train MAE = 1851.3523, Val MAE = 1855.9284, Train R² = 0.8985, Val R² = 0.9053
   Fold 3: Train MAE = 1826.9622, Val MAE = 1838.9569, Train R² = 0.8982, Val R² = 0.8949
   Fold 4: Train MAE = 1887.0751, Val MAE = 1863.8154, Train R² = 0.8925, Val R² = 0.9003
   Fold 5: Train MAE = 1852.4674, Val MAE = 1875.7340, Train R² = 0.8978, Val R² = 0.8908
   Fold 6: Train MAE = 1906.0254, Val MAE = 1951.0583, Train R² = 0.8951, Val R² = 0.8703
   Fold 7: Train MAE = 1882.0241, Val MAE = 1919.2450, Train R² = 0.8932, Val R² = 0.8934
→ Avg Train MAE: 1867.8377 | Avg Val MAE: 1887.8155 | Avg Train R²: 0.8957 | Avg Val R²: 0.8925

► Combination 33/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 512, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 6841.9343, Val MAE = 6860.7862, Train R² = -0.0165, Val R² = -0.0155

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 6842.7072, Val MAE = 6861.5596, Train R² = -0.0167, Val R² = -0.0130

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1894.3886, Val MAE = 1904.9234, Train R² = 0.8914, Val R² = 0.8900
   Fold 4: Train MAE = 1901.9935, Val MAE = 1881.8344, Train R² = 0.8893, Val R² = 0.8980
   Fold 5: Train MAE = 1863.1649, Val MAE = 1889.8334, Train R² = 0.8935, Val R² = 0.8862

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1873.2762, Val MAE = 1913.9076, Train R² = 0.8950, Val R² = 0.8707

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 6852.6054, Val MAE = 6801.8898, Train R² = -0.0161, Val R² = -0.0166
→ Avg Train MAE: 4010.0100 | Avg Val MAE: 4016.3906 | Avg Train R²: 0.5028 | Avg Val R²: 0.5000

► Combination 34/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 5), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 512, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1941.6409, Val MAE = 1977.0750, Train R² = 0.8845, Val R² = 0.8829

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1939.9081, Val MAE = 1933.4745, Train R² = 0.8843, Val R² = 0.8937

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1960.2098, Val MAE = 1958.1890, Train R² = 0.8828, Val R² = 0.8847

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1967.3070, Val MAE = 1932.8681, Train R² = 0.8824, Val R² = 0.8919

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1973.4188, Val MAE = 1991.6192, Train R² = 0.8819, Val R² = 0.8750

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1925.2251, Val MAE = 1973.5906, Train R² = 0.8905, Val R² = 0.8651

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1935.3232, Val MAE = 1978.4052, Train R² = 0.8850, Val R² = 0.8812
→ Avg Train MAE: 1949.0047 | Avg Val MAE: 1963.6031 | Avg Train R²: 0.8845 | Avg Val R²: 0.8821

► Combination 35/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10,), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 128, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2083.3397, Val MAE = 2095.7385, Train R² = 0.8638, Val R² = 0.8697

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2092.5086, Val MAE = 2059.7290, Train R² = 0.8623, Val R² = 0.8752

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2066.5964, Val MAE = 2064.8400, Train R² = 0.8679, Val R² = 0.8711

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2310.1432, Val MAE = 2265.6145, Train R² = 0.8399, Val R² = 0.8543

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2068.2335, Val MAE = 2077.9447, Train R² = 0.8696, Val R² = 0.8631

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2165.7264, Val MAE = 2223.7633, Train R² = 0.8583, Val R² = 0.8347

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2054.2193, Val MAE = 2118.2523, Train R² = 0.8679, Val R² = 0.8545
→ Avg Train MAE: 2120.1096 | Avg Val MAE: 2129.4117 | Avg Train R²: 0.8614 | Avg Val R²: 0.8604

► Combination 36/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 512, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2623.2963, Val MAE = 2622.9860, Train R² = 0.8031, Val R² = 0.8102

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2601.4843, Val MAE = 2582.6286, Train R² = 0.7954, Val R² = 0.8106

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2633.5963, Val MAE = 2627.6735, Train R² = 0.8023, Val R² = 0.8072

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2333.2352, Val MAE = 2265.5803, Train R² = 0.8346, Val R² = 0.8509

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2634.0790, Val MAE = 2645.0617, Train R² = 0.8049, Val R² = 0.7965

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2612.6284, Val MAE = 2667.9910, Train R² = 0.8074, Val R² = 0.7852

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2591.4581, Val MAE = 2686.7158, Train R² = 0.8016, Val R² = 0.7756
→ Avg Train MAE: 2575.6825 | Avg Val MAE: 2585.5196 | Avg Train R²: 0.8070 | Avg Val R²: 0.8052

► Combination 37/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 128, 'alpha': 0.003}
   Fold 1: Train MAE = 1897.6718, Val MAE = 1918.8878, Train R² = 0.8916, Val R² = 0.8912
   Fold 2: Train MAE = 1908.0360, Val MAE = 1911.4351, Train R² = 0.8899, Val R² = 0.8981

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 16419.5125, Val MAE = 16456.3397, Train R² = -2.8506, Val R² = -2.8158

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 16421.2334, Val MAE = 16450.0121, Train R² = -2.8363, Val R² = -2.9033

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 16406.5735, Val MAE = 16534.0328, Train R² = -2.8409, Val R² = -2.8736

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16426.1162, Val MAE = 16418.5778, Train R² = -2.8565, Val R² = -2.7818
   Fold 7: Train MAE = 1945.1908, Val MAE = 1984.0131, Train R² = 0.8868, Val R² = 0.8848
→ Avg Train MAE: 10203.4763 | Avg Val MAE: 10239.0426 | Avg Train R²: -1.2451 | Avg Val R²: -1.2429

► Combination 38/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6, 4), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 512, 'alpha': 0.003}
   Fold 1: Train MAE = 16888.7522, Val MAE = 16833.4627, Train R² = -2.9983, Val R² = -3.0514
   Fold 2: Train MAE = 16902.2466, Val MAE = 16752.5046, Train R² = -3.0119, Val R² = -2.9697

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1984.3381, Val MAE = 1981.0703, Train R² = 0.8801, Val R² = 0.8825

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2027.8125, Val MAE = 2003.7324, Train R² = 0.8772, Val R² = 0.8881

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1971.4646, Val MAE = 1989.7828, Train R² = 0.8812, Val R² = 0.8749

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1894.1262, Val MAE = 1945.6076, Train R² = 0.8925, Val R² = 0.8690
   Fold 7: Train MAE = 16878.0650, Val MAE = 16897.5846, Train R² = -3.0048, Val R² = -3.0111
→ Avg Train MAE: 8363.8293 | Avg Val MAE: 8343.3921 | Avg Train R²: -0.7834 | Avg Val R²: -0.7882

► Combination 39/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 512, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2112.6031, Val MAE = 2140.4692, Train R² = 0.8651, Val R² = 0.8676

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2100.9692, Val MAE = 2081.8886, Train R² = 0.8649, Val R² = 0.8765

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2175.4874, Val MAE = 2164.2201, Train R² = 0.8619, Val R² = 0.8663

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2101.7261, Val MAE = 2050.1917, Train R² = 0.8672, Val R² = 0.8785

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2075.5945, Val MAE = 2082.3643, Train R² = 0.8687, Val R² = 0.8625

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2232.7434, Val MAE = 2300.2120, Train R² = 0.8508, Val R² = 0.8273

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2115.2816, Val MAE = 2184.7624, Train R² = 0.8665, Val R² = 0.8549
→ Avg Train MAE: 2130.6293 | Avg Val MAE: 2143.4440 | Avg Train R²: 0.8636 | Avg Val R²: 0.8619

► Combination 40/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 256, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1882.0798, Val MAE = 1923.4554, Train R² = 0.8914, Val R² = 0.8884

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1865.2082, Val MAE = 1866.7256, Train R² = 0.8914, Val R² = 0.8993
   Fold 3: Train MAE = 1943.5221, Val MAE = 1945.9791, Train R² = 0.8886, Val R² = 0.8881
   Fold 4: Train MAE = 2178.8130, Val MAE = 2133.9125, Train R² = 0.8658, Val R² = 0.8802
   Fold 5: Train MAE = 1854.4807, Val MAE = 1893.3350, Train R² = 0.8941, Val R² = 0.8865

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1883.6905, Val MAE = 1933.3628, Train R² = 0.8942, Val R² = 0.8702
   Fold 7: Train MAE = 1895.9196, Val MAE = 1940.6954, Train R² = 0.8895, Val R² = 0.8867
→ Avg Train MAE: 1929.1020 | Avg Val MAE: 1948.2094 | Avg Train R²: 0.8879 | Avg Val R²: 0.8856

► Combination 41/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 128, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1940.7090, Val MAE = 1964.5325, Train R² = 0.8844, Val R² = 0.8846

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1942.6642, Val MAE = 1942.2240, Train R² = 0.8834, Val R² = 0.8918
   Fold 3: Train MAE = 1978.1535, Val MAE = 1978.9105, Train R² = 0.8824, Val R² = 0.8837

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2430.2266, Val MAE = 2366.3697, Train R² = 0.8239, Val R² = 0.8408

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1875.4879, Val MAE = 1894.7983, Train R² = 0.8946, Val R² = 0.8883

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1860.2290, Val MAE = 1915.5945, Train R² = 0.8964, Val R² = 0.8738

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1945.3690, Val MAE = 1988.5871, Train R² = 0.8847, Val R² = 0.8808
→ Avg Train MAE: 1996.1199 | Avg Val MAE: 2007.2881 | Avg Train R²: 0.8785 | Avg Val R²: 0.8777

► Combination 42/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (6, 4), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 128, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2000.9632, Val MAE = 2026.7027, Train R² = 0.8776, Val R² = 0.8783

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16720.3289, Val MAE = 16570.5869, Train R² = -2.9474, Val R² = -2.9055
   Fold 3: Train MAE = 1976.8109, Val MAE = 1974.1342, Train R² = 0.8819, Val R² = 0.8838
   Fold 4: Train MAE = 2018.5228, Val MAE = 1978.3218, Train R² = 0.8769, Val R² = 0.8871

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1931.9425, Val MAE = 1949.4112, Train R² = 0.8872, Val R² = 0.8805

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1989.1801, Val MAE = 2029.6698, Train R² = 0.8827, Val R² = 0.8603

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1955.9507, Val MAE = 2003.8623, Train R² = 0.8837, Val R² = 0.8793
→ Avg Train MAE: 4084.8142 | Avg Val MAE: 4076.0984 | Avg Train R²: 0.3346 | Avg Val R²: 0.3377

► Combination 43/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 128, 'alpha': 0.0001}
   Fold 1: Train MAE = 1904.3265, Val MAE = 1935.0729, Train R² = 0.8903, Val R² = 0.8893
   Fold 2: Train MAE = 1841.5642, Val MAE = 1852.1558, Train R² = 0.8964, Val R² = 0.9046
   Fold 3: Train MAE = 1898.8067, Val MAE = 1908.1582, Train R² = 0.8904, Val R² = 0.8888
   Fold 4: Train MAE = 1774.4478, Val MAE = 1783.3234, Train R² = 0.9023, Val R² = 0.9071
   Fold 5: Train MAE = 1868.9010, Val MAE = 1894.9034, Train R² = 0.8928, Val R² = 0.8863
   Fold 6: Train MAE = 1891.4679, Val MAE = 1929.1943, Train R² = 0.8944, Val R² = 0.8700
   Fold 7: Train MAE = 1914.0259, Val MAE = 1954.2774, Train R² = 0.8897, Val R² = 0.8882
→ Avg Train MAE: 1870.5057 | Avg Val MAE: 1893.8694 | Avg Train R²: 0.8938 | Avg Val R²: 0.8906

► Combination 44/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 128, 'alpha': 0.0003}
   Fold 1: Train MAE = 1895.3709, Val MAE = 1918.7173, Train R² = 0.8914, Val R² = 0.8908
   Fold 2: Train MAE = 1907.9972, Val MAE = 1911.1524, Train R² = 0.8899, Val R² = 0.8981

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 16419.5125, Val MAE = 16456.3397, Train R² = -2.8506, Val R² = -2.8158

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 16421.2334, Val MAE = 16450.0121, Train R² = -2.8363, Val R² = -2.9033

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 16406.5735, Val MAE = 16534.0328, Train R² = -2.8409, Val R² = -2.8736

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16426.1162, Val MAE = 16418.5778, Train R² = -2.8565, Val R² = -2.7818
   Fold 7: Train MAE = 1944.6059, Val MAE = 1983.0552, Train R² = 0.8869, Val R² = 0.8848
→ Avg Train MAE: 10203.0585 | Avg Val MAE: 10238.8410 | Avg Train R²: -1.2452 | Avg Val R²: -1.2430

► Combination 45/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7,), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 512, 'alpha': 0.001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2869.3284, Val MAE = 2861.5244, Train R² = 0.7601, Val R² = 0.7675

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2871.7119, Val MAE = 2863.1890, Train R² = 0.7582, Val R² = 0.7731

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 3081.6205, Val MAE = 3107.3829, Train R² = 0.7276, Val R² = 0.7312

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2874.5165, Val MAE = 2798.1452, Train R² = 0.7590, Val R² = 0.7796

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 3074.1378, Val MAE = 3082.8425, Train R² = 0.7310, Val R² = 0.7227

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2748.8964, Val MAE = 2787.9026, Train R² = 0.7829, Val R² = 0.7625

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2861.8204, Val MAE = 2951.5562, Train R² = 0.7645, Val R² = 0.7366
→ Avg Train MAE: 2911.7188 | Avg Val MAE: 2921.7918 | Avg Train R²: 0.7548 | Avg Val R²: 0.7533

► Combination 46/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 256, 'alpha': 0.0003}
   Fold 1: Train MAE = 1884.6421, Val MAE = 1914.0212, Train R² = 0.8948, Val R² = 0.8922
   Fold 2: Train MAE = 1755.9746, Val MAE = 1757.8949, Train R² = 0.9061, Val R² = 0.9128
   Fold 3: Train MAE = 1863.1654, Val MAE = 1868.0465, Train R² = 0.8938, Val R² = 0.8920
   Fold 4: Train MAE = 1881.3705, Val MAE = 1857.4886, Train R² = 0.8923, Val R² = 0.9005
   Fold 5: Train MAE = 1816.6409, Val MAE = 1838.0136, Train R² = 0.8993, Val R² = 0.8926
   Fold 6: Train MAE = 1900.6242, Val MAE = 1942.9460, Train R² = 0.8949, Val R² = 0.8699
   Fold 7: Train MAE = 1995.7314, Val MAE = 2030.1664, Train R² = 0.8820, Val R² = 0.8815
→ Avg Train MAE: 1871.1642 | Avg Val MAE: 1886.9396 | Avg Train R²: 0.8948 | Avg Val R²: 0.8916

► Combination 47/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 128, 'alpha': 0.003}
   Fold 1: Train MAE = 2198.7928, Val MAE = 2235.9622, Train R² = 0.8621, Val R² = 0.8586
   Fold 2: Train MAE = 1945.0342, Val MAE = 1928.8200, Train R² = 0.8875, Val R² = 0.8997
   Fold 3: Train MAE = 1895.4501, Val MAE = 1908.8820, Train R² = 0.8941, Val R² = 0.8903
   Fold 4: Train MAE = 1854.2218, Val MAE = 1840.6766, Train R² = 0.8951, Val R² = 0.9024
   Fold 5: Train MAE = 1898.0950, Val MAE = 1919.4332, Train R² = 0.8914, Val R² = 0.8848
   Fold 6: Train MAE = 1869.4493, Val MAE = 1919.7189, Train R² = 0.8953, Val R² = 0.8693
   Fold 7: Train MAE = 2226.0211, Val MAE = 2265.8624, Train R² = 0.8604, Val R² = 0.8560
→ Avg Train MAE: 1983.8663 | Avg Val MAE: 2002.7650 | Avg Train R²: 0.8837 | Avg Val R²: 0.8802

► Combination 48/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 128, 'alpha': 0.01}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 15974.7625, Val MAE = 15919.6661, Train R² = -2.6826, Val R² = -2.7290

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 15988.3005, Val MAE = 15838.5538, Train R² = -2.6949, Val R² = -2.6544
   Fold 3: Train MAE = 7004.7918, Val MAE = 7107.2912, Train R² = -0.0000, Val R² = -0.0001
   Fold 4: Train MAE = 7038.5980, Val MAE = 6990.5568, Train R² = -0.0000, Val R² = -0.0000
   Fold 5: Train MAE = 7000.9530, Val MAE = 6977.1339, Train R² = -0.0002, Val R² = -0.0007

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 15969.9767, Val MAE = 15962.4163, Train R² = -2.7000, Val R² = -2.6293

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 15964.1102, Val MAE = 15983.5673, Train R² = -2.6882, Val R² = -2.6942
→ Avg Train MAE: 12134.4990 | Avg Val MAE: 12111.3122 | Avg Train R²: -1.5380 | Avg Val R²: -1.5297

► Combination 49/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (6, 4), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 512, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2146.9585, Val MAE = 2190.9878, Train R² = 0.8689, Val R² = 0.8677

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2007.6607, Val MAE = 1998.9878, Train R² = 0.8778, Val R² = 0.8877

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2012.4194, Val MAE = 2016.6091, Train R² = 0.8775, Val R² = 0.8805

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2213.1338, Val MAE = 2166.4961, Train R² = 0.8610, Val R² = 0.8727

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1984.6586, Val MAE = 2006.4029, Train R² = 0.8811, Val R² = 0.8738

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2036.3207, Val MAE = 2087.6488, Train R² = 0.8774, Val R² = 0.8534

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1991.9193, Val MAE = 2040.6841, Train R² = 0.8799, Val R² = 0.8748
→ Avg Train MAE: 2056.1530 | Avg Val MAE: 2072.5452 | Avg Train R²: 0.8748 | Avg Val R²: 0.8729

► Combination 50/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6, 4), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 256, 'alpha': 0.003}
   Fold 1: Train MAE = 16888.7571, Val MAE = 16833.4676, Train R² = -2.9983, Val R² = -3.0514
   Fold 2: Train MAE = 16902.2515, Val MAE = 16752.5094, Train R² = -3.0119, Val R² = -2.9697

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2054.6985, Val MAE = 2053.6424, Train R² = 0.8717, Val R² = 0.8744

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1963.2830, Val MAE = 1948.7798, Train R² = 0.8846, Val R² = 0.8938

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2037.0040, Val MAE = 2046.0984, Train R² = 0.8733, Val R² = 0.8675

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2041.5092, Val MAE = 2089.2897, Train R² = 0.8778, Val R² = 0.8535
   Fold 7: Train MAE = 16878.0698, Val MAE = 16897.5894, Train R² = -3.0048, Val R² = -3.0111
→ Avg Train MAE: 8395.0819 | Avg Val MAE: 8374.4824 | Avg Train R²: -0.7868 | Avg Val R²: -0.7919

► Combination 51/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6, 4), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 256, 'alpha': 0.001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 16660.9997, Val MAE = 16605.7102, Train R² = -2.9180, Val R² = -2.9694

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16674.4963, Val MAE = 16524.7543, Train R² = -2.9312, Val R² = -2.8895
   Fold 3: Train MAE = 1987.6886, Val MAE = 1991.2672, Train R² = 0.8870, Val R² = 0.8861
   Fold 4: Train MAE = 1939.9930, Val MAE = 1923.7125, Train R² = 0.8916, Val R² = 0.8978
   Fold 5: Train MAE = 1770.5334, Val MAE = 1797.5003, Train R² = 0.9051, Val R² = 0.8981
   Fold 6: Train MAE = 1913.6960, Val MAE = 1960.8627, Train R² = 0.8936, Val R² = 0.8681

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 16650.3151, Val MAE = 16669.8348, Train R² = -2.9243, Val R² = -2.9305
→ Avg Train MAE: 8228.2460 | Avg Val MAE: 8210.5203 | Avg Train R²: -0.7423 | Avg Val R²: -0.7485

► Combination 52/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 6), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 128, 'alpha': 0.01}
   Fold 1: Train MAE = 1894.5203, Val MAE = 1920.7726, Train R² = 0.8907, Val R² = 0.8900
   Fold 2: Train MAE = 1888.2985, Val MAE = 1892.3374, Train R² = 0.8899, Val R² = 0.8980
   Fold 3: Train MAE = 1919.0317, Val MAE = 1926.4881, Train R² = 0.8898, Val R² = 0.8888
   Fold 4: Train MAE = 1858.6828, Val MAE = 1844.7993, Train R² = 0.8953, Val R² = 0.9019
   Fold 5: Train MAE = 1928.2170, Val MAE = 1946.6703, Train R² = 0.8901, Val R² = 0.8829

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 15968.8384, Val MAE = 15961.2785, Train R² = -2.6997, Val R² = -2.6290
   Fold 7: Train MAE = 1898.8930, Val MAE = 1936.0178, Train R² = 0.8921, Val R² = 0.8913
→ Avg Train MAE: 3908.0688 | Avg Val MAE: 3918.3377 | Avg Train R²: 0.3784 | Avg Val R²: 0.3891

► Combination 53/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 256, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1925.5999, Val MAE = 1953.2542, Train R² = 0.8880, Val R² = 0.8869

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1924.4583, Val MAE = 1925.9663, Train R² = 0.8864, Val R² = 0.8945

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1931.9840, Val MAE = 1934.3800, Train R² = 0.8884, Val R² = 0.8879

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 16785.3815, Val MAE = 16814.1604, Train R² = -2.9635, Val R² = -3.0333

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1922.3434, Val MAE = 1941.8749, Train R² = 0.8882, Val R² = 0.8821

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1834.4826, Val MAE = 1879.4842, Train R² = 0.8993, Val R² = 0.8760

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1922.7876, Val MAE = 1959.2591, Train R² = 0.8881, Val R² = 0.8860
→ Avg Train MAE: 4035.2911 | Avg Val MAE: 4058.3399 | Avg Train R²: 0.3393 | Avg Val R²: 0.3257

► Combination 54/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 128, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 16432.1837, Val MAE = 16376.8957, Train R² = -2.8384, Val R² = -2.8881

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2041.4844, Val MAE = 2032.3600, Train R² = 0.8741, Val R² = 0.8844
   Fold 3: Train MAE = 1904.5264, Val MAE = 1912.2405, Train R² = 0.8905, Val R² = 0.8890
   Fold 4: Train MAE = 1971.8448, Val MAE = 1954.1734, Train R² = 0.8847, Val R² = 0.8928
   Fold 5: Train MAE = 1880.1119, Val MAE = 1903.0949, Train R² = 0.8928, Val R² = 0.8862
   Fold 6: Train MAE = 1962.7010, Val MAE = 2010.0095, Train R² = 0.8870, Val R² = 0.8623

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2202.0748, Val MAE = 2271.3565, Train R² = 0.8608, Val R² = 0.8493
→ Avg Train MAE: 4056.4181 | Avg Val MAE: 4065.7329 | Avg Train R²: 0.3502 | Avg Val R²: 0.3394

► Combination 55/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 128, 'alpha': 0.003}
   Fold 1: Train MAE = 7023.3774, Val MAE = 7045.8949, Train R² = -0.0000, Val R² = -0.0000
   Fold 2: Train MAE = 1739.6672, Val MAE = 1739.2666, Train R² = 0.8957, Val R² = 0.9033
   Fold 3: Train MAE = 1820.4682, Val MAE = 1850.4904, Train R² = 0.8991, Val R² = 0.8932
   Fold 4: Train MAE = 1858.4727, Val MAE = 1850.1328, Train R² = 0.8949, Val R² = 0.9009
   Fold 5: Train MAE = 1838.3189, Val MAE = 1861.4816, Train R² = 0.8988, Val R² = 0.8923
   Fold 6: Train MAE = 1848.3883, Val MAE = 1889.6627, Train R² = 0.8998, Val R² = 0.8749
   Fold 7: Train MAE = 7022.2096, Val MAE = 6968.8006, Train R² = -0.0000, Val R² = -0.0001
→ Avg Train MAE: 3307.2718 | Avg Val MAE: 3315.1042 | Avg Train R²: 0.6412 | Avg Val R²: 0.6378

► Combination 56/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7,), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 512, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 3590.0364, Val MAE = 3586.6409, Train R² = 0.6438, Val R² = 0.6530

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 3588.2594, Val MAE = 3583.3542, Train R² = 0.6427, Val R² = 0.6538

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 3830.2960, Val MAE = 3863.4794, Train R² = 0.5969, Val R² = 0.6005

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 3587.3973, Val MAE = 3517.5132, Train R² = 0.6432, Val R² = 0.6624

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 3822.3972, Val MAE = 3829.3638, Train R² = 0.6005, Val R² = 0.5932

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 3446.8757, Val MAE = 3468.7957, Train R² = 0.6723, Val R² = 0.6546

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 3586.4238, Val MAE = 3641.1178, Train R² = 0.6482, Val R² = 0.6237
→ Avg Train MAE: 3635.9551 | Avg Val MAE: 3641.4664 | Avg Train R²: 0.6354 | Avg Val R²: 0.6345

► Combination 57/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 512, 'alpha': 0.01}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1817.6555, Val MAE = 1858.3566, Train R² = 0.8990, Val R² = 0.8954

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1922.2815, Val MAE = 1934.2314, Train R² = 0.8890, Val R² = 0.8980

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1922.2453, Val MAE = 1928.9229, Train R² = 0.8891, Val R² = 0.8884
   Fold 4: Train MAE = 1897.4919, Val MAE = 1880.8835, Train R² = 0.8903, Val R² = 0.8987

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1955.5616, Val MAE = 1975.1866, Train R² = 0.8872, Val R² = 0.8800

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16766.9600, Val MAE = 16759.4219, Train R² = -2.9763, Val R² = -2.8985

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1921.3980, Val MAE = 1953.3220, Train R² = 0.8883, Val R² = 0.8866
→ Avg Train MAE: 4029.0848 | Avg Val MAE: 4041.4750 | Avg Train R²: 0.3381 | Avg Val R²: 0.3498

► Combination 58/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 6), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 256, 'alpha': 0.01}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2180.5238, Val MAE = 2194.0928, Train R² = 0.8556, Val R² = 0.8594

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2407.8933, Val MAE = 2374.8494, Train R² = 0.8267, Val R² = 0.8402

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2682.8811, Val MAE = 2676.9717, Train R² = 0.7918, Val R² = 0.7965

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2600.3330, Val MAE = 2541.6083, Train R² = 0.8106, Val R² = 0.8259

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2556.8963, Val MAE = 2574.9118, Train R² = 0.8111, Val R² = 0.8025
   Fold 6: Train MAE = 16880.8825, Val MAE = 16873.3443, Train R² = -3.0169, Val R² = -2.9380

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2196.3582, Val MAE = 2272.5864, Train R² = 0.8528, Val R² = 0.8355
→ Avg Train MAE: 4500.8240 | Avg Val MAE: 4501.1950 | Avg Train R²: 0.2760 | Avg Val R²: 0.2888

► Combination 59/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 5), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 256, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2836.6636, Val MAE = 2822.2618, Train R² = 0.7677, Val R² = 0.7769

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2838.9814, Val MAE = 2828.1855, Train R² = 0.7661, Val R² = 0.7812

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2868.6808, Val MAE = 2880.3247, Train R² = 0.7619, Val R² = 0.7660

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 3006.1830, Val MAE = 2935.8369, Train R² = 0.7412, Val R² = 0.7608

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2766.0553, Val MAE = 2777.0862, Train R² = 0.7797, Val R² = 0.7712

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2657.4224, Val MAE = 2709.6494, Train R² = 0.8006, Val R² = 0.7796

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2970.8894, Val MAE = 3058.5398, Train R² = 0.7511, Val R² = 0.7218
→ Avg Train MAE: 2849.2680 | Avg Val MAE: 2858.8406 | Avg Train R²: 0.7669 | Avg Val R²: 0.7654

► Combination 60/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 512, 'alpha': 0.01}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2566.1296, Val MAE = 2562.2718, Train R² = 0.7978, Val R² = 0.8051

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2566.1454, Val MAE = 2551.3657, Train R² = 0.7964, Val R² = 0.8126

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2694.9219, Val MAE = 2705.5274, Train R² = 0.7821, Val R² = 0.7861

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2354.6050, Val MAE = 2281.8279, Train R² = 0.8282, Val R² = 0.8459

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2771.6210, Val MAE = 2776.2566, Train R² = 0.7746, Val R² = 0.7668

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2554.7803, Val MAE = 2605.2596, Train R² = 0.8088, Val R² = 0.7879

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2563.4471, Val MAE = 2666.8342, Train R² = 0.8018, Val R² = 0.7728
→ Avg Train MAE: 2581.6643 | Avg Val MAE: 2592.7633 | Avg Train R²: 0.7985 | Avg Val R²: 0.7967

► Combination 61/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 512, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1923.1977, Val MAE = 1955.6587, Train R² = 0.8863, Val R² = 0.8842

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1955.6034, Val MAE = 1957.8416, Train R² = 0.8840, Val R² = 0.8928

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1983.1128, Val MAE = 1979.9138, Train R² = 0.8813, Val R² = 0.8833

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1931.7120, Val MAE = 1904.5413, Train R² = 0.8865, Val R² = 0.8962

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1993.1848, Val MAE = 2010.1721, Train R² = 0.8792, Val R² = 0.8724

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16812.9249, Val MAE = 16805.3868, Train R² = -2.9926, Val R² = -2.9144

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1952.3674, Val MAE = 1997.4774, Train R² = 0.8854, Val R² = 0.8821
→ Avg Train MAE: 4078.8719 | Avg Val MAE: 4087.2845 | Avg Train R²: 0.3300 | Avg Val R²: 0.3424

► Combination 62/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 128, 'alpha': 0.001}
   Fold 1: Train MAE = 16887.3725, Val MAE = 16832.0830, Train R² = -2.9978, Val R² = -3.0509
   Fold 2: Train MAE = 16900.8657, Val MAE = 16751.1237, Train R² = -3.0114, Val R² = -2.9692

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2530.3470, Val MAE = 2525.3919, Train R² = 0.8113, Val R² = 0.8164

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2656.3913, Val MAE = 2587.5690, Train R² = 0.7926, Val R² = 0.8106

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2528.4335, Val MAE = 2538.7095, Train R² = 0.8144, Val R² = 0.8057

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2472.9599, Val MAE = 2534.9777, Train R² = 0.8215, Val R² = 0.8004
   Fold 7: Train MAE = 16876.6838, Val MAE = 16896.2035, Train R² = -3.0043, Val R² = -3.0107
→ Avg Train MAE: 8693.2934 | Avg Val MAE: 8666.5797 | Avg Train R²: -0.8248 | Avg Val R²: -0.8282

► Combination 63/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 512, 'alpha': 0.01}
   Fold 1: Train MAE = 16888.7147, Val MAE = 16833.4252, Train R² = -2.9983, Val R² = -3.0514
   Fold 2: Train MAE = 16902.2093, Val MAE = 16752.4673, Train R² = -3.0118, Val R² = -2.9696
   Fold 3: Train MAE = 16874.4987, Val MAE = 16911.3260, Train R² = -3.0107, Val R² = -2.9736
   Fold 4: Train MAE = 16876.7825, Val MAE = 16905.5613, Train R² = -2.9959, Val R² = -3.0663
   Fold 5: Train MAE = 16861.5519, Val MAE = 16989.0114, Train R² = -3.0007, Val R² = -3.0339
   Fold 6: Train MAE = 16882.1754, Val MAE = 16874.6372, Train R² = -3.0173, Val R² = -2.9385
   Fold 7: Train MAE = 16878.0286, Val MAE = 16897.5482, Train R² = -3.0048, Val R² = -3.0111
→ Avg Train MAE: 16880.5659 | Avg Val MAE: 16880.5681 | Avg Train R²: -3.0057 | Avg Val R²: -3.0064

► Combination 64/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 5), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 512, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 3680.8208, Val MAE = 3675.3603, Train R² = 0.6269, Val R² = 0.6368

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 3680.4385, Val MAE = 3677.8459, Train R² = 0.6268, Val R² = 0.6372

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 3887.8785, Val MAE = 3920.7239, Train R² = 0.5902, Val R² = 0.5940

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 3907.8124, Val MAE = 3842.7030, Train R² = 0.5870, Val R² = 0.6038

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 3896.4654, Val MAE = 3901.0107, Train R² = 0.5917, Val R² = 0.5847

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 3294.4668, Val MAE = 3314.0603, Train R² = 0.6983, Val R² = 0.6810

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 3865.7438, Val MAE = 3914.7332, Train R² = 0.5986, Val R² = 0.5763
→ Avg Train MAE: 3744.8037 | Avg Val MAE: 3749.4910 | Avg Train R²: 0.6171 | Avg Val R²: 0.6163

► Combination 65/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 256, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1770.7666, Val MAE = 1805.9991, Train R² = 0.9016, Val R² = 0.8993

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1802.5813, Val MAE = 1800.2062, Train R² = 0.8992, Val R² = 0.9078

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1976.0577, Val MAE = 1974.7706, Train R² = 0.8827, Val R² = 0.8839

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1926.2438, Val MAE = 1901.3494, Train R² = 0.8872, Val R² = 0.8965

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1990.8664, Val MAE = 2010.5246, Train R² = 0.8801, Val R² = 0.8731

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16790.3609, Val MAE = 16782.8228, Train R² = -2.9846, Val R² = -2.9066

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1798.0542, Val MAE = 1827.4682, Train R² = 0.9006, Val R² = 0.8996
→ Avg Train MAE: 4007.8473 | Avg Val MAE: 4014.7344 | Avg Train R²: 0.3381 | Avg Val R²: 0.3505

► Combination 66/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9,), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 512, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 3769.2522, Val MAE = 3759.3917, Train R² = 0.6099, Val R² = 0.6199

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 3775.7479, Val MAE = 3776.7784, Train R² = 0.6092, Val R² = 0.6188

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 3447.2302, Val MAE = 3479.6588, Train R² = 0.6684, Val R² = 0.6720

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 3200.4568, Val MAE = 3127.8756, Train R² = 0.7086, Val R² = 0.7291

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 3451.9155, Val MAE = 3462.7988, Train R² = 0.6701, Val R² = 0.6618

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 3308.9539, Val MAE = 3331.4181, Train R² = 0.6944, Val R² = 0.6764

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 3769.9405, Val MAE = 3816.7451, Train R² = 0.6142, Val R² = 0.5915
→ Avg Train MAE: 3531.9281 | Avg Val MAE: 3536.3809 | Avg Train R²: 0.6535 | Avg Val R²: 0.6528

► Combination 67/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 512, 'alpha': 0.001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 3568.1769, Val MAE = 3567.9217, Train R² = 0.6514, Val R² = 0.6601

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 3576.4290, Val MAE = 3567.2046, Train R² = 0.6491, Val R² = 0.6612
   Fold 3: Train MAE = 16876.2522, Val MAE = 16913.0795, Train R² = -3.0114, Val R² = -2.9743
   Fold 4: Train MAE = 16877.9594, Val MAE = 16906.7383, Train R² = -2.9963, Val R² = -3.0668
   Fold 5: Train MAE = 16863.3050, Val MAE = 16990.7645, Train R² = -3.0013, Val R² = -3.0345
   Fold 6: Train MAE = 16882.8607, Val MAE = 16875.3225, Train R² = -3.0176, Val R² = -2.9387

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 3569.8416, Val MAE = 3631.5462, Train R² = 0.6546, Val R² = 0.6283
→ Avg Train MAE: 11173.5464 | Avg Val MAE: 11207.5110 | Avg Train R²: -1.4388 | Avg Val R²: -1.4378

► Combination 68/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 256, 'alpha': 0.01}
   Fold 1: Train MAE = 16889.7546, Val MAE = 16834.4651, Train R² = -2.9987, Val R² = -3.0517
   Fold 2: Train MAE = 16903.2490, Val MAE = 16753.5069, Train R² = -3.0122, Val R² = -2.9700
   Fold 3: Train MAE = 16875.5382, Val MAE = 16912.3656, Train R² = -3.0111, Val R² = -2.9740
   Fold 4: Train MAE = 16877.8220, Val MAE = 16906.6009, Train R² = -2.9962, Val R² = -3.0667
   Fold 5: Train MAE = 16862.5912, Val MAE = 16990.0508, Train R² = -3.0010, Val R² = -3.0343
   Fold 6: Train MAE = 16883.2148, Val MAE = 16875.6766, Train R² = -3.0177, Val R² = -2.9388
   Fold 7: Train MAE = 16879.0678, Val MAE = 16898.5874, Train R² = -3.0052, Val R² = -3.0115
→ Avg Train MAE: 16881.6054 | Avg Val MAE: 16881.6076 | Avg Train R²: -3.0060 | Avg Val R²: -3.0067

► Combination 69/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 256, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 16431.4569, Val MAE = 16376.1690, Train R² = -2.8382, Val R² = -2.8878

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16444.9585, Val MAE = 16295.2162, Train R² = -2.8511, Val R² = -2.8098
   Fold 3: Train MAE = 7005.9468, Val MAE = 7108.4449, Train R² = -0.0000, Val R² = -0.0000
   Fold 4: Train MAE = 7030.4590, Val MAE = 6983.0742, Train R² = -0.0000, Val R² = -0.0000
   Fold 5: Train MAE = 7007.1528, Val MAE = 6982.8206, Train R² = -0.0001, Val R² = -0.0006

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16426.6411, Val MAE = 16419.1027, Train R² = -2.8567, Val R² = -2.7820

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 16420.7669, Val MAE = 16440.2863, Train R² = -2.8442, Val R² = -2.8504
→ Avg Train MAE: 12395.3403 | Avg Val MAE: 12372.1591 | Avg Train R²: -1.6272 | Avg Val R²: -1.6186

► Combination 70/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6, 4), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 512, 'alpha': 0.001}
   Fold 1: Train MAE = 16889.2696, Val MAE = 16833.9801, Train R² = -2.9985, Val R² = -3.0516
   Fold 2: Train MAE = 16902.7639, Val MAE = 16753.0219, Train R² = -3.0120, Val R² = -2.9698

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2233.7483, Val MAE = 2227.1731, Train R² = 0.8469, Val R² = 0.8513

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2315.2581, Val MAE = 2258.3652, Train R² = 0.8493, Val R² = 0.8627

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2233.0243, Val MAE = 2245.7833, Train R² = 0.8499, Val R² = 0.8420
   Fold 6: Train MAE = 16882.4916, Val MAE = 16874.9534, Train R² = -3.0174, Val R² = -2.9386
   Fold 7: Train MAE = 16878.5823, Val MAE = 16898.1019, Train R² = -3.0050, Val R² = -3.0113
→ Avg Train MAE: 10619.3054 | Avg Val MAE: 10584.4827 | Avg Train R²: -1.3553 | Avg Val R²: -1.3451

► Combination 71/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8,), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 512, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 3874.7977, Val MAE = 3861.3339, Train R² = 0.5865, Val R² = 0.5974

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 3875.0918, Val MAE = 3883.2649, Train R² = 0.5860, Val R² = 0.5943

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 4804.4055, Val MAE = 4860.4689, Train R² = 0.4355, Val R² = 0.4371

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 3950.5528, Val MAE = 3887.8405, Train R² = 0.5775, Val R² = 0.5936

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 4766.7038, Val MAE = 4732.7178, Train R² = 0.4420, Val R² = 0.4404

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 3939.7794, Val MAE = 3964.6517, Train R² = 0.5827, Val R² = 0.5657

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 3872.5738, Val MAE = 3912.9792, Train R² = 0.5910, Val R² = 0.5701
→ Avg Train MAE: 4154.8435 | Avg Val MAE: 4157.6081 | Avg Train R²: 0.5430 | Avg Val R²: 0.5427

► Combination 72/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 128, 'alpha': 0.003}
   Fold 1: Train MAE = 1891.6132, Val MAE = 1919.1553, Train R² = 0.8903, Val R² = 0.8890

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1896.0199, Val MAE = 1901.1560, Train R² = 0.8894, Val R² = 0.8976
   Fold 3: Train MAE = 2536.1680, Val MAE = 2533.8185, Train R² = 0.8228, Val R² = 0.8282
   Fold 4: Train MAE = 1893.4302, Val MAE = 1874.4486, Train R² = 0.8899, Val R² = 0.8986
   Fold 5: Train MAE = 2544.3261, Val MAE = 2546.6258, Train R² = 0.8237, Val R² = 0.8189
   Fold 6: Train MAE = 1886.3132, Val MAE = 1931.8173, Train R² = 0.8935, Val R² = 0.8688
   Fold 7: Train MAE = 1929.1297, Val MAE = 1969.9899, Train R² = 0.8875, Val R² = 0.8852
→ Avg Train MAE: 2082.4286 | Avg Val MAE: 2096.7159 | Avg Train R²: 0.8710 | Avg Val R²: 0.8695

► Combination 73/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10,), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 512, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 5769.2262, Val MAE = 5773.2471, Train R² = 0.1705, Val R² = 0.1768

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 5667.8667, Val MAE = 5686.9520, Train R² = 0.1819, Val R² = 0.1865

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 4812.0040, Val MAE = 4870.7692, Train R² = 0.4258, Val R² = 0.4271

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 6409.9365, Val MAE = 6415.4514, Train R² = -0.0706, Val R² = -0.0735

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 4818.5712, Val MAE = 4785.5320, Train R² = 0.4283, Val R² = 0.4268

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 5566.8043, Val MAE = 5532.4418, Train R² = 0.2792, Val R² = 0.2708

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 5806.9002, Val MAE = 5773.3744, Train R² = 0.1683, Val R² = 0.1635
→ Avg Train MAE: 5550.1870 | Avg Val MAE: 5548.2526 | Avg Train R²: 0.2262 | Avg Val R²: 0.2254

► Combination 74/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9,), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 128, 'alpha': 0.001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2647.0797, Val MAE = 2639.1539, Train R² = 0.7976, Val R² = 0.8071

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2504.3725, Val MAE = 2475.8742, Train R² = 0.8137, Val R² = 0.8278

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2346.8194, Val MAE = 2340.5011, Train R² = 0.8318, Val R² = 0.8366

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2299.5318, Val MAE = 2234.2911, Train R² = 0.8407, Val R² = 0.8558

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2346.3500, Val MAE = 2357.5312, Train R² = 0.8334, Val R² = 0.8250

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2292.2780, Val MAE = 2361.7528, Train R² = 0.8408, Val R² = 0.8175

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2492.6136, Val MAE = 2573.4419, Train R² = 0.8184, Val R² = 0.7963
→ Avg Train MAE: 2418.4350 | Avg Val MAE: 2426.0781 | Avg Train R²: 0.8252 | Avg Val R²: 0.8237

► Combination 75/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8,), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 256, 'alpha': 0.01}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2578.2764, Val MAE = 2570.6858, Train R² = 0.7941, Val R² = 0.8032

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2641.9886, Val MAE = 2621.0199, Train R² = 0.7939, Val R² = 0.8084

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2858.5500, Val MAE = 2872.1973, Train R² = 0.7601, Val R² = 0.7637

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2717.9361, Val MAE = 2648.9338, Train R² = 0.7855, Val R² = 0.8040

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2932.4838, Val MAE = 2942.6432, Train R² = 0.7515, Val R² = 0.7430

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2702.0552, Val MAE = 2744.4439, Train R² = 0.7905, Val R² = 0.7703

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2674.2514, Val MAE = 2765.9837, Train R² = 0.7916, Val R² = 0.7650
→ Avg Train MAE: 2729.3631 | Avg Val MAE: 2737.9868 | Avg Train R²: 0.7810 | Avg Val R²: 0.7797

► Combination 76/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 512, 'alpha': 0.01}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 16775.8520, Val MAE = 16720.5625, Train R² = -2.9584, Val R² = -3.0106

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16789.3468, Val MAE = 16639.6047, Train R² = -2.9718, Val R² = -2.9298

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 16761.6368, Val MAE = 16798.4642, Train R² = -2.9706, Val R² = -2.9341

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 16763.9218, Val MAE = 16792.7007, Train R² = -2.9559, Val R² = -3.0255

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 16748.6895, Val MAE = 16876.1491, Train R² = -2.9606, Val R² = -2.9937

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16769.3130, Val MAE = 16761.7749, Train R² = -2.9771, Val R² = -2.8993

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 16765.1677, Val MAE = 16784.6874, Train R² = -2.9648, Val R² = -2.9710
→ Avg Train MAE: 16767.7039 | Avg Val MAE: 16767.7062 | Avg Train R²: -2.9656 | Avg Val R²: -2.9663

► Combination 77/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9,), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 128, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2705.1233, Val MAE = 2690.1595, Train R² = 0.7851, Val R² = 0.7953

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2560.4258, Val MAE = 2539.9943, Train R² = 0.8022, Val R² = 0.8170

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2688.7692, Val MAE = 2686.0987, Train R² = 0.7910, Val R² = 0.7957

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2492.1423, Val MAE = 2422.9615, Train R² = 0.8112, Val R² = 0.8292

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2687.2810, Val MAE = 2700.7827, Train R² = 0.7930, Val R² = 0.7842

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2593.1191, Val MAE = 2648.7060, Train R² = 0.8038, Val R² = 0.7826

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2553.1737, Val MAE = 2632.2532, Train R² = 0.8062, Val R² = 0.7820
→ Avg Train MAE: 2611.4335 | Avg Val MAE: 2617.2794 | Avg Train R²: 0.7989 | Avg Val R²: 0.7980

► Combination 78/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 128, 'alpha': 0.0001}
   Fold 1: Train MAE = 1908.3361, Val MAE = 1930.7992, Train R² = 0.8905, Val R² = 0.8896
   Fold 2: Train MAE = 1909.7394, Val MAE = 1917.4519, Train R² = 0.8899, Val R² = 0.8964
   Fold 3: Train MAE = 1921.5379, Val MAE = 1931.2800, Train R² = 0.8901, Val R² = 0.8885

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1891.0489, Val MAE = 1902.1486, Train R² = 0.8937, Val R² = 0.8984
   Fold 5: Train MAE = 2166.3173, Val MAE = 2179.2239, Train R² = 0.8703, Val R² = 0.8642
   Fold 6: Train MAE = 1792.4678, Val MAE = 1840.6191, Train R² = 0.9057, Val R² = 0.8817
   Fold 7: Train MAE = 1884.5795, Val MAE = 1923.0299, Train R² = 0.8933, Val R² = 0.8927
→ Avg Train MAE: 1924.8610 | Avg Val MAE: 1946.3647 | Avg Train R²: 0.8905 | Avg Val R²: 0.8874

► Combination 79/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7,), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 256, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 5952.9940, Val MAE = 5955.9742, Train R² = 0.1187, Val R² = 0.1244

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 5954.7221, Val MAE = 5967.4487, Train R² = 0.1184, Val R² = 0.1233

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 8821.5809, Val MAE = 8873.0101, Train R² = -0.7154, Val R² = -0.7098

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 5964.9891, Val MAE = 5935.6348, Train R² = 0.1144, Val R² = 0.1168

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 8817.7791, Val MAE = 8904.9858, Train R² = -0.7122, Val R² = -0.7322

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 5766.2789, Val MAE = 5730.2288, Train R² = 0.2401, Val R² = 0.2329

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 5972.4016, Val MAE = 5935.3856, Train R² = 0.1184, Val R² = 0.1148
→ Avg Train MAE: 6750.1065 | Avg Val MAE: 6757.5240 | Avg Train R²: -0.1025 | Avg Val R²: -0.1043

► Combination 80/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 512, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 9314.9937, Val MAE = 9271.4424, Train R² = -0.8412, Val R² = -0.8511

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 9326.9995, Val MAE = 9195.9682, Train R² = -0.8461, Val R² = -0.8211

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1929.3199, Val MAE = 1928.6525, Train R² = 0.8857, Val R² = 0.8870

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1926.3502, Val MAE = 1900.3379, Train R² = 0.8865, Val R² = 0.8959

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1897.6669, Val MAE = 1932.5002, Train R² = 0.8888, Val R² = 0.8813

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1910.5801, Val MAE = 1954.6163, Train R² = 0.8917, Val R² = 0.8677

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 9306.5185, Val MAE = 9319.0408, Train R² = -0.8420, Val R² = -0.8455
→ Avg Train MAE: 5087.4898 | Avg Val MAE: 5071.7940 | Avg Train R²: 0.1462 | Avg Val R²: 0.1449

► Combination 81/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (6, 4), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 256, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1958.8422, Val MAE = 1981.5661, Train R² = 0.8848, Val R² = 0.8835

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16674.4818, Val MAE = 16524.7398, Train R² = -2.9312, Val R² = -2.8895

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1950.8118, Val MAE = 1954.1409, Train R² = 0.8869, Val R² = 0.8868

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 3782.8281, Val MAE = 3713.8594, Train R² = 0.6099, Val R² = 0.6282
   Fold 5: Train MAE = 1967.3739, Val MAE = 1989.3247, Train R² = 0.8849, Val R² = 0.8776

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1963.1180, Val MAE = 2010.3463, Train R² = 0.8868, Val R² = 0.8620
   Fold 7: Train MAE = 1936.6021, Val MAE = 1974.2273, Train R² = 0.8871, Val R² = 0.8852
→ Avg Train MAE: 4319.1511 | Avg Val MAE: 4306.8863 | Avg Train R²: 0.3013 | Avg Val R²: 0.3048

► Combination 82/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9,), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 256, 'alpha': 0.001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2240.5803, Val MAE = 2262.8966, Train R² = 0.8521, Val R² = 0.8553

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2247.1513, Val MAE = 2204.4215, Train R² = 0.8512, Val R² = 0.8652

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2063.7630, Val MAE = 2060.3301, Train R² = 0.8695, Val R² = 0.8734

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2055.5535, Val MAE = 2005.2705, Train R² = 0.8699, Val R² = 0.8812

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2056.8226, Val MAE = 2068.3780, Train R² = 0.8709, Val R² = 0.8644

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2039.5044, Val MAE = 2101.4696, Train R² = 0.8743, Val R² = 0.8494

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2085.6444, Val MAE = 2143.0847, Train R² = 0.8668, Val R² = 0.8546
→ Avg Train MAE: 2112.7171 | Avg Val MAE: 2120.8359 | Avg Train R²: 0.8650 | Avg Val R²: 0.8634

► Combination 83/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 128, 'alpha': 0.001}
   Fold 1: Train MAE = 1904.6856, Val MAE = 1935.5541, Train R² = 0.8903, Val R² = 0.8893

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1857.0184, Val MAE = 1863.3344, Train R² = 0.8949, Val R² = 0.9025
   Fold 3: Train MAE = 1901.5503, Val MAE = 1910.1683, Train R² = 0.8900, Val R² = 0.8884
   Fold 4: Train MAE = 1771.4678, Val MAE = 1789.4846, Train R² = 0.9028, Val R² = 0.9072
   Fold 5: Train MAE = 1887.1454, Val MAE = 1906.9338, Train R² = 0.8919, Val R² = 0.8855
   Fold 6: Train MAE = 1864.1223, Val MAE = 1904.5646, Train R² = 0.8976, Val R² = 0.8719
   Fold 7: Train MAE = 1891.4580, Val MAE = 1936.8312, Train R² = 0.8909, Val R² = 0.8890
→ Avg Train MAE: 1868.2068 | Avg Val MAE: 1892.4101 | Avg Train R²: 0.8941 | Avg Val R²: 0.8905

► Combination 84/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10,), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 256, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2106.0520, Val MAE = 2131.5491, Train R² = 0.8643, Val R² = 0.8664

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1989.8998, Val MAE = 1961.8775, Train R² = 0.8750, Val R² = 0.8867

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1999.3379, Val MAE = 1994.7936, Train R² = 0.8769, Val R² = 0.8801

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2292.8154, Val MAE = 2231.4692, Train R² = 0.8444, Val R² = 0.8590

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1994.2573, Val MAE = 2010.8427, Train R² = 0.8785, Val R² = 0.8721

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2085.2036, Val MAE = 2138.0725, Train R² = 0.8700, Val R² = 0.8458

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1981.8092, Val MAE = 2048.8024, Train R² = 0.8769, Val R² = 0.8665
→ Avg Train MAE: 2064.1965 | Avg Val MAE: 2073.9153 | Avg Train R²: 0.8694 | Avg Val R²: 0.8681

► Combination 85/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6, 4), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 128, 'alpha': 0.001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 15975.6478, Val MAE = 15920.5510, Train R² = -2.6829, Val R² = -2.7293

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 15989.1723, Val MAE = 15839.4257, Train R² = -2.6952, Val R² = -2.6547
   Fold 3: Train MAE = 2243.4202, Val MAE = 2230.1360, Train R² = 0.8568, Val R² = 0.8615
   Fold 4: Train MAE = 1876.2078, Val MAE = 1860.7903, Train R² = 0.8932, Val R² = 0.9003
   Fold 5: Train MAE = 1759.4483, Val MAE = 1792.0281, Train R² = 0.9053, Val R² = 0.8989
   Fold 6: Train MAE = 7003.7541, Val MAE = 6957.1036, Train R² = -0.0003, Val R² = -0.0002

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 15965.0116, Val MAE = 15984.4688, Train R² = -2.6885, Val R² = -2.6945
→ Avg Train MAE: 8687.5232 | Avg Val MAE: 8654.9291 | Avg Train R²: -0.7731 | Avg Val R²: -0.7740

► Combination 86/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 5), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 256, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2022.0031, Val MAE = 2052.3192, Train R² = 0.8752, Val R² = 0.8764

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2032.3933, Val MAE = 2009.4635, Train R² = 0.8735, Val R² = 0.8847

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1891.1126, Val MAE = 1884.7755, Train R² = 0.8880, Val R² = 0.8905

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1900.6698, Val MAE = 1888.8479, Train R² = 0.8878, Val R² = 0.8954

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2006.3708, Val MAE = 2023.1773, Train R² = 0.8764, Val R² = 0.8696

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2155.3862, Val MAE = 2209.3036, Train R² = 0.8692, Val R² = 0.8429

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2024.1799, Val MAE = 2083.0487, Train R² = 0.8756, Val R² = 0.8673
→ Avg Train MAE: 2004.5880 | Avg Val MAE: 2021.5622 | Avg Train R²: 0.8780 | Avg Val R²: 0.8753

► Combination 87/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 128, 'alpha': 0.01}
   Fold 1: Train MAE = 7028.6502, Val MAE = 7051.1556, Train R² = -0.0000, Val R² = -0.0001
   Fold 2: Train MAE = 7027.0456, Val MAE = 7075.5089, Train R² = -0.0000, Val R² = -0.0003
   Fold 3: Train MAE = 1859.3821, Val MAE = 1881.4250, Train R² = 0.8982, Val R² = 0.8916
   Fold 4: Train MAE = 1887.3176, Val MAE = 1877.3451, Train R² = 0.8941, Val R² = 0.8996
   Fold 5: Train MAE = 1818.1736, Val MAE = 1849.3698, Train R² = 0.8983, Val R² = 0.8909
   Fold 6: Train MAE = 1807.2576, Val MAE = 1855.5446, Train R² = 0.9037, Val R² = 0.8786
   Fold 7: Train MAE = 7020.5728, Val MAE = 6967.1563, Train R² = -0.0000, Val R² = -0.0001
→ Avg Train MAE: 4064.0571 | Avg Val MAE: 4079.6436 | Avg Train R²: 0.5134 | Avg Val R²: 0.5086

► Combination 88/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 512, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2229.1494, Val MAE = 2260.5424, Train R² = 0.8604, Val R² = 0.8597

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2112.2689, Val MAE = 2086.8181, Train R² = 0.8641, Val R² = 0.8763

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2154.2929, Val MAE = 2147.7860, Train R² = 0.8575, Val R² = 0.8618

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2276.0048, Val MAE = 2220.8374, Train R² = 0.8532, Val R² = 0.8662

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2146.2130, Val MAE = 2154.6454, Train R² = 0.8596, Val R² = 0.8530

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2249.7414, Val MAE = 2314.8484, Train R² = 0.8574, Val R² = 0.8314

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 14815.2531, Val MAE = 14834.8055, Train R² = -2.3144, Val R² = -2.3200
→ Avg Train MAE: 3997.5605 | Avg Val MAE: 4002.8976 | Avg Train R²: 0.4054 | Avg Val R²: 0.4041

► Combination 89/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 6), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 128, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2063.8482, Val MAE = 2110.1715, Train R² = 0.8758, Val R² = 0.8733

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2104.9423, Val MAE = 2077.0931, Train R² = 0.8720, Val R² = 0.8844

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2039.0251, Val MAE = 2041.6890, Train R² = 0.8735, Val R² = 0.8764

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2177.4639, Val MAE = 2141.4117, Train R² = 0.8611, Val R² = 0.8740

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2028.6793, Val MAE = 2043.5662, Train R² = 0.8754, Val R² = 0.8687

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2347.7154, Val MAE = 2420.1949, Train R² = 0.8398, Val R² = 0.8169

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1785.4409, Val MAE = 1824.9682, Train R² = 0.9017, Val R² = 0.8987
→ Avg Train MAE: 2078.1593 | Avg Val MAE: 2094.1563 | Avg Train R²: 0.8713 | Avg Val R²: 0.8704

► Combination 90/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 512, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2120.6547, Val MAE = 2147.3883, Train R² = 0.8626, Val R² = 0.8651

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2348.6614, Val MAE = 2316.9230, Train R² = 0.8418, Val R² = 0.8543

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2559.6420, Val MAE = 2556.9838, Train R² = 0.8181, Val R² = 0.8232

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2075.9414, Val MAE = 2027.9121, Train R² = 0.8692, Val R² = 0.8809

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2561.7719, Val MAE = 2566.6777, Train R² = 0.8200, Val R² = 0.8144

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2528.3138, Val MAE = 2587.0501, Train R² = 0.8265, Val R² = 0.8007

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2111.9556, Val MAE = 2183.9826, Train R² = 0.8646, Val R² = 0.8516
→ Avg Train MAE: 2329.5630 | Avg Val MAE: 2340.9882 | Avg Train R²: 0.8433 | Avg Val R²: 0.8415

► Combination 91/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 5), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 512, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 3680.8208, Val MAE = 3675.3603, Train R² = 0.6269, Val R² = 0.6368

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 3680.4385, Val MAE = 3677.8459, Train R² = 0.6268, Val R² = 0.6372

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 3887.8785, Val MAE = 3920.7239, Train R² = 0.5902, Val R² = 0.5940

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 3907.8124, Val MAE = 3842.7030, Train R² = 0.5870, Val R² = 0.6038

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 3896.4654, Val MAE = 3901.0107, Train R² = 0.5917, Val R² = 0.5847

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 3294.4668, Val MAE = 3314.0603, Train R² = 0.6983, Val R² = 0.6810

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 3865.7438, Val MAE = 3914.7332, Train R² = 0.5986, Val R² = 0.5763
→ Avg Train MAE: 3744.8037 | Avg Val MAE: 3749.4910 | Avg Train R²: 0.6171 | Avg Val R²: 0.6163

► Combination 92/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 256, 'alpha': 0.003}
   Fold 1: Train MAE = 16888.7243, Val MAE = 16833.4348, Train R² = -2.9983, Val R² = -3.0514
   Fold 2: Train MAE = 16902.2190, Val MAE = 16752.4769, Train R² = -3.0119, Val R² = -2.9697
   Fold 3: Train MAE = 16874.5084, Val MAE = 16911.3357, Train R² = -3.0107, Val R² = -2.9736
   Fold 4: Train MAE = 16876.7923, Val MAE = 16905.5712, Train R² = -2.9959, Val R² = -3.0663
   Fold 5: Train MAE = 16861.5616, Val MAE = 16989.0212, Train R² = -3.0007, Val R² = -3.0339
   Fold 6: Train MAE = 16882.1850, Val MAE = 16874.6468, Train R² = -3.0173, Val R² = -2.9385
   Fold 7: Train MAE = 16878.0381, Val MAE = 16897.5577, Train R² = -3.0048, Val R² = -3.0111
→ Avg Train MAE: 16880.5755 | Avg Val MAE: 16880.5778 | Avg Train R²: -3.0057 | Avg Val R²: -3.0064

► Combination 93/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 128, 'alpha': 0.01}
   Fold 1: Train MAE = 1883.9359, Val MAE = 1911.4916, Train R² = 0.8920, Val R² = 0.8907
   Fold 2: Train MAE = 1859.9885, Val MAE = 1867.3366, Train R² = 0.8970, Val R² = 0.9040
   Fold 3: Train MAE = 1850.4151, Val MAE = 1856.7761, Train R² = 0.8946, Val R² = 0.8921
   Fold 4: Train MAE = 1839.4657, Val MAE = 1830.8829, Train R² = 0.8963, Val R² = 0.9026
   Fold 5: Train MAE = 1843.9656, Val MAE = 1874.3464, Train R² = 0.8972, Val R² = 0.8900
   Fold 6: Train MAE = 1869.1784, Val MAE = 1915.1651, Train R² = 0.8963, Val R² = 0.8709
   Fold 7: Train MAE = 1889.5884, Val MAE = 1928.0727, Train R² = 0.8903, Val R² = 0.8892
→ Avg Train MAE: 1862.3625 | Avg Val MAE: 1883.4388 | Avg Train R²: 0.8948 | Avg Val R²: 0.8914

► Combination 94/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 256, 'alpha': 0.003}
   Fold 1: Train MAE = 1805.0535, Val MAE = 1861.0265, Train R² = 0.9044, Val R² = 0.8960

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 1833.4195, Val MAE = 1850.6521, Train R² = 0.8981, Val R² = 0.9029
   Fold 3: Train MAE = 1891.7623, Val MAE = 1900.4699, Train R² = 0.8924, Val R² = 0.8901
   Fold 4: Train MAE = 1877.7208, Val MAE = 1858.4191, Train R² = 0.8921, Val R² = 0.9001
   Fold 5: Train MAE = 1855.3662, Val MAE = 1875.3223, Train R² = 0.8953, Val R² = 0.8886
   Fold 6: Train MAE = 1905.1725, Val MAE = 1947.1721, Train R² = 0.8940, Val R² = 0.8694
   Fold 7: Train MAE = 1856.3221, Val MAE = 1896.7060, Train R² = 0.8940, Val R² = 0.8936
→ Avg Train MAE: 1860.6881 | Avg Val MAE: 1884.2526 | Avg Train R²: 0.8958 | Avg Val R²: 0.8915

► Combination 95/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10, 8, 6), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 512, 'alpha': 0.01}
   Fold 1: Train MAE = 7021.8073, Val MAE = 7044.3296, Train R² = -0.0000, Val R² = -0.0000
   Fold 2: Train MAE = 7020.9025, Val MAE = 7068.6584, Train R² = -0.0000, Val R² = -0.0002
   Fold 3: Train MAE = 1783.3898, Val MAE = 1802.5661, Train R² = 0.9019, Val R² = 0.8965
   Fold 4: Train MAE = 1906.9815, Val MAE = 1892.8049, Train R² = 0.8938, Val R² = 0.8996
   Fold 5: Train MAE = 1784.5650, Val MAE = 1819.6770, Train R² = 0.9016, Val R² = 0.8942
   Fold 6: Train MAE = 1800.6312, Val MAE = 1844.0862, Train R² = 0.9051, Val R² = 0.8819
   Fold 7: Train MAE = 7020.6798, Val MAE = 6967.2638, Train R² = -0.0000, Val R² = -0.0001
→ Avg Train MAE: 4048.4224 | Avg Val MAE: 4062.7694 | Avg Train R²: 0.5146 | Avg Val R²: 0.5103

► Combination 96/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 5), 'activation': 'relu', 'learning_rate_init': 0.002, 'batch_size': 512, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2192.2714, Val MAE = 2212.8571, Train R² = 0.8532, Val R² = 0.8567

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2202.2135, Val MAE = 2165.3510, Train R² = 0.8512, Val R² = 0.8648

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2197.4423, Val MAE = 2189.0073, Train R² = 0.8511, Val R² = 0.8566

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2158.5791, Val MAE = 2105.6767, Train R² = 0.8555, Val R² = 0.8686

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2171.0355, Val MAE = 2184.5324, Train R² = 0.8562, Val R² = 0.8488

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2348.8486, Val MAE = 2413.0986, Train R² = 0.8466, Val R² = 0.8211

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2196.4643, Val MAE = 2269.3528, Train R² = 0.8543, Val R² = 0.8395
→ Avg Train MAE: 2209.5507 | Avg Val MAE: 2219.9823 | Avg Train R²: 0.8526 | Avg Val R²: 0.8509

► Combination 97/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 128, 'alpha': 0.0003}
   Fold 1: Train MAE = 16888.7257, Val MAE = 16833.4362, Train R² = -2.9983, Val R² = -3.0514
   Fold 2: Train MAE = 16902.2204, Val MAE = 16752.4783, Train R² = -3.0119, Val R² = -2.9697
   Fold 3: Train MAE = 16874.5097, Val MAE = 16911.3371, Train R² = -3.0107, Val R² = -2.9736
   Fold 4: Train MAE = 16876.7939, Val MAE = 16905.5727, Train R² = -2.9959, Val R² = -3.0663
   Fold 5: Train MAE = 16861.5630, Val MAE = 16989.0225, Train R² = -3.0007, Val R² = -3.0339
   Fold 6: Train MAE = 16882.1863, Val MAE = 16874.6482, Train R² = -3.0173, Val R² = -2.9385
   Fold 7: Train MAE = 16878.0394, Val MAE = 16897.5590, Train R² = -3.0048, Val R² = -3.0111
→ Avg Train MAE: 16880.5769 | Avg Val MAE: 16880.5792 | Avg Train R²: -3.0057 | Avg Val R²: -3.0064

► Combination 98/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 7, 5), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 512, 'alpha': 0.003}
   Fold 1: Train MAE = 1884.6942, Val MAE = 1914.5370, Train R² = 0.8913, Val R² = 0.8894
   Fold 2: Train MAE = 1911.7035, Val MAE = 1910.3518, Train R² = 0.8897, Val R² = 0.8984
   Fold 3: Train MAE = 1827.5365, Val MAE = 1851.3788, Train R² = 0.9002, Val R² = 0.8936
   Fold 4: Train MAE = 1910.9182, Val MAE = 1887.2678, Train R² = 0.8894, Val R² = 0.8986
   Fold 5: Train MAE = 1826.5711, Val MAE = 1852.3493, Train R² = 0.8974, Val R² = 0.8900
   Fold 6: Train MAE = 1854.6110, Val MAE = 1899.5819, Train R² = 0.8986, Val R² = 0.8732
   Fold 7: Train MAE = 1891.2272, Val MAE = 1922.1703, Train R² = 0.8916, Val R² = 0.8909
→ Avg Train MAE: 1872.4660 | Avg Val MAE: 1891.0910 | Avg Train R²: 0.8940 | Avg Val R²: 0.8906

► Combination 99/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 256, 'alpha': 0.0003}
   Fold 1: Train MAE = 2005.1066, Val MAE = 2036.4720, Train R² = 0.8853, Val R² = 0.8843

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16446.3667, Val MAE = 16296.6245, Train R² = -2.8516, Val R² = -2.8102
   Fold 3: Train MAE = 1884.5453, Val MAE = 1900.1630, Train R² = 0.8929, Val R² = 0.8895
   Fold 4: Train MAE = 1884.9610, Val MAE = 1871.7793, Train R² = 0.8928, Val R² = 0.8998
   Fold 5: Train MAE = 1902.5166, Val MAE = 1925.4847, Train R² = 0.8921, Val R² = 0.8857
   Fold 6: Train MAE = 1842.0539, Val MAE = 1888.4028, Train R² = 0.9006, Val R² = 0.8744
   Fold 7: Train MAE = 1997.6525, Val MAE = 2034.2329, Train R² = 0.8860, Val R² = 0.8849
→ Avg Train MAE: 3994.7432 | Avg Val MAE: 3993.3085 | Avg Train R²: 0.3569 | Avg Val R²: 0.3584

► Combination 100/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 128, 'alpha': 0.0003}
   Fold 1: Train MAE = 2018.3656, Val MAE = 2047.7601, Train R² = 0.8842, Val R² = 0.8831
   Fold 2: Train MAE = 2001.0221, Val MAE = 2005.3853, Train R² = 0.8834, Val R² = 0.8931
   Fold 3: Train MAE = 1929.3413, Val MAE = 1950.9277, Train R² = 0.8911, Val R² = 0.8876
   Fold 4: Train MAE = 2025.8165, Val MAE = 2007.2960, Train R² = 0.8841, Val R² = 0.8922
   Fold 5: Train MAE = 1940.3064, Val MAE = 1960.3514, Train R² = 0.8907, Val R² = 0.8835

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 15967.7906, Val MAE = 15960.2311, Train R² = -2.6993, Val R² = -2.6286
   Fold 7: Train MAE = 2007.2767, Val MAE = 2051.0791, Train R² = 0.8854, Val R² = 0.8829
→ Avg Train MAE: 3984.2742 | Avg Val MAE: 3997.5758 | Avg Train R²: 0.3742 | Avg Val R²: 0.3848

► Combination 101/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (5, 3, 2), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 128, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1858.6733, Val MAE = 1893.3208, Train R² = 0.8930, Val R² = 0.8922
   Fold 2: Train MAE = 1826.3443, Val MAE = 1812.8357, Train R² = 0.8977, Val R² = 0.9061

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1846.9358, Val MAE = 1840.8524, Train R² = 0.8959, Val R² = 0.8961

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 1961.7716, Val MAE = 1930.1424, Train R² = 0.8834, Val R² = 0.8930

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2049.3753, Val MAE = 2061.2161, Train R² = 0.8724, Val R² = 0.8658

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16790.4154, Val MAE = 16782.8773, Train R² = -2.9846, Val R² = -2.9066

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 1810.5943, Val MAE = 1846.2235, Train R² = 0.9003, Val R² = 0.8977
→ Avg Train MAE: 4020.5872 | Avg Val MAE: 4023.9240 | Avg Train R²: 0.3369 | Avg Val R²: 0.3492

► Combination 102/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 5), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 128, 'alpha': 0.0001}
   Fold 1: Train MAE = 1885.4448, Val MAE = 1913.9260, Train R² = 0.8912, Val R² = 0.8899
   Fold 2: Train MAE = 1916.1485, Val MAE = 1914.7516, Train R² = 0.8882, Val R² = 0.8969
   Fold 3: Train MAE = 1922.6238, Val MAE = 1931.9923, Train R² = 0.8899, Val R² = 0.8885
   Fold 4: Train MAE = 1909.0884, Val MAE = 1890.3065, Train R² = 0.8893, Val R² = 0.8971
   Fold 5: Train MAE = 1765.8412, Val MAE = 1793.6123, Train R² = 0.9042, Val R² = 0.8980
   Fold 6: Train MAE = 1869.9050, Val MAE = 1918.0248, Train R² = 0.8960, Val R² = 0.8705
   Fold 7: Train MAE = 1898.3027, Val MAE = 1939.3102, Train R² = 0.8901, Val R² = 0.8883
→ Avg Train MAE: 1881.0506 | Avg Val MAE: 1900.2748 | Avg Train R²: 0.8927 | Avg Val R²: 0.8899

► Combination 103/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7,), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 512, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 3590.0364, Val MAE = 3586.6409, Train R² = 0.6438, Val R² = 0.6530

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 3588.2594, Val MAE = 3583.3542, Train R² = 0.6427, Val R² = 0.6538

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 3830.2960, Val MAE = 3863.4794, Train R² = 0.5969, Val R² = 0.6005

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 3587.3973, Val MAE = 3517.5132, Train R² = 0.6432, Val R² = 0.6624

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 3822.3972, Val MAE = 3829.3638, Train R² = 0.6005, Val R² = 0.5932

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 3446.8757, Val MAE = 3468.7957, Train R² = 0.6723, Val R² = 0.6546

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 3586.4238, Val MAE = 3641.1178, Train R² = 0.6482, Val R² = 0.6237
→ Avg Train MAE: 3635.9551 | Avg Val MAE: 3641.4664 | Avg Train R²: 0.6354 | Avg Val R²: 0.6345

► Combination 104/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4), 'activation': 'relu', 'learning_rate_init': 0.001, 'batch_size': 128, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 1826.6741, Val MAE = 1851.7881, Train R² = 0.8974, Val R² = 0.8970
   Fold 2: Train MAE = 1852.8263, Val MAE = 1841.2085, Train R² = 0.8949, Val R² = 0.9031

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1896.6421, Val MAE = 1900.8437, Train R² = 0.8904, Val R² = 0.8892
   Fold 4: Train MAE = 1793.6559, Val MAE = 1814.6423, Train R² = 0.9010, Val R² = 0.9053
   Fold 5: Train MAE = 1897.1109, Val MAE = 1917.6314, Train R² = 0.8905, Val R² = 0.8839

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 1900.9462, Val MAE = 1943.6086, Train R² = 0.8927, Val R² = 0.8688
   Fold 7: Train MAE = 1949.4446, Val MAE = 1992.4036, Train R² = 0.8845, Val R² = 0.8804
→ Avg Train MAE: 1873.9000 | Avg Val MAE: 1894.5895 | Avg Train R²: 0.8931 | Avg Val R²: 0.8897

► Combination 105/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (10,), 'activation': 'relu', 'learning_rate_init': 0.01, 'batch_size': 256, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2106.2313, Val MAE = 2131.8434, Train R² = 0.8643, Val R² = 0.8663

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2034.1979, Val MAE = 2007.7020, Train R² = 0.8695, Val R² = 0.8815

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 1999.3067, Val MAE = 1994.7080, Train R² = 0.8769, Val R² = 0.8801

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2292.8040, Val MAE = 2231.4478, Train R² = 0.8444, Val R² = 0.8590

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 1994.2267, Val MAE = 2010.7896, Train R² = 0.8785, Val R² = 0.8721

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2085.2255, Val MAE = 2138.0540, Train R² = 0.8700, Val R² = 0.8458

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2041.4222, Val MAE = 2101.9259, Train R² = 0.8713, Val R² = 0.8609
→ Avg Train MAE: 2079.0592 | Avg Val MAE: 2088.0672 | Avg Train R²: 0.8679 | Avg Val R²: 0.8665

► Combination 106/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8,), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 256, 'alpha': 0.0003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2702.1825, Val MAE = 2693.2120, Train R² = 0.7845, Val R² = 0.7935

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2666.0991, Val MAE = 2646.3027, Train R² = 0.7907, Val R² = 0.8053

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 3167.7723, Val MAE = 3199.3360, Train R² = 0.7117, Val R² = 0.7150

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 2717.9312, Val MAE = 2648.9310, Train R² = 0.7855, Val R² = 0.8040

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 3237.3275, Val MAE = 3244.0510, Train R² = 0.7048, Val R² = 0.6963

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2670.3485, Val MAE = 2714.2624, Train R² = 0.7947, Val R² = 0.7742

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2693.9888, Val MAE = 2787.0403, Train R² = 0.7893, Val R² = 0.7625
→ Avg Train MAE: 2836.5214 | Avg Val MAE: 2847.5908 | Avg Train R²: 0.7659 | Avg Val R²: 0.7644

► Combination 107/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (8, 6, 4, 2), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 256, 'alpha': 0.003}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 16661.9950, Val MAE = 16606.7055, Train R² = -2.9184, Val R² = -2.9697

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 16675.4912, Val MAE = 16525.7491, Train R² = -2.9316, Val R² = -2.8898

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 16647.7849, Val MAE = 16684.6123, Train R² = -2.9304, Val R² = -2.8944

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 4: Train MAE = 16650.0695, Val MAE = 16678.8484, Train R² = -2.9159, Val R² = -2.9846

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 16634.8373, Val MAE = 16762.2968, Train R² = -2.9205, Val R² = -2.9535

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 16655.4584, Val MAE = 16647.9203, Train R² = -2.9368, Val R² = -2.8601

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 16651.3141, Val MAE = 16670.8337, Train R² = -2.9246, Val R² = -2.9309
→ Avg Train MAE: 16653.8501 | Avg Val MAE: 16653.8523 | Avg Train R²: -2.9255 | Avg Val R²: -2.9261

► Combination 108/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 7, 5), 'activation': 'relu', 'learning_rate_init': 0.005, 'batch_size': 128, 'alpha': 0.003}
   Fold 1: Train MAE = 1894.7702, Val MAE = 1922.8263, Train R² = 0.8916, Val R² = 0.8904
   Fold 2: Train MAE = 1884.1368, Val MAE = 1886.7411, Train R² = 0.8938, Val R² = 0.9005
   Fold 3: Train MAE = 1840.1698, Val MAE = 1850.4659, Train R² = 0.8984, Val R² = 0.8915
   Fold 4: Train MAE = 1886.8141, Val MAE = 1866.1317, Train R² = 0.8923, Val R² = 0.9003
   Fold 5: Train MAE = 1855.0482, Val MAE = 1883.1513, Train R² = 0.8966, Val R² = 0.8899
   Fold 6: Train MAE = 1785.8028, Val MAE = 1840.0742, Train R² = 0.9076, Val R² = 0.8820
   Fold 7: Train MAE = 1892.6449, Val MAE = 1929.0339, Train R² = 0.8916, Val R² = 0.8906
→ Avg Train MAE: 1862.7695 | Avg Val MAE: 1882.6321 | Avg Train R²: 0.8960 | Avg Val R²: 0.8922

► Combination 109/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (7, 5, 3), 'activation': 'relu', 'learning_rate_init': 0.0005, 'batch_size': 256, 'alpha': 0.01}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 1: Train MAE = 2361.0188, Val MAE = 2368.2252, Train R² = 0.8332, Val R² = 0.8405

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 2: Train MAE = 2360.4463, Val MAE = 2317.2888, Train R² = 0.8323, Val R² = 0.8468

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 3: Train MAE = 2489.9517, Val MAE = 2478.0770, Train R² = 0.8144, Val R² = 0.8195
   Fold 4: Train MAE = 16875.8818, Val MAE = 16904.6606, Train R² = -2.9955, Val R² = -3.0660

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 5: Train MAE = 2259.3913, Val MAE = 2275.8539, Train R² = 0.8399, Val R² = 0.8305

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 6: Train MAE = 2631.3416, Val MAE = 2682.0870, Train R² = 0.8024, Val R² = 0.7814

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

   Fold 7: Train MAE = 2356.7957, Val MAE = 2443.3469, Train R² = 0.8362, Val R² = 0.8151
→ Avg Train MAE: 4476.4039 | Avg Val MAE: 4495.6485 | Avg Train R²: 0.2804 | Avg Val R²: 0.2668

► Combination 110/300: {'solver': 'adam', 'early_stopping': True, 'random_state': 1907, 'validation_fraction': 0.1, 'n_iter_no_change': 7, 'hidden_layer_sizes': (9, 7, 5), 'activation': 'relu', 'learning_rate_init': 0.003, 'batch_size': 128, 'alpha': 0.0001}

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:788: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")

   Fold 1: Train MAE = 2008.7300, Val MAE = 2040.0758, Train R² = 0.8758, Val R² = 0.8770

In [ ]:
f = open( "CV_NN2.py", "w")
f.write(repr(results))
f.close()

In [ ]:
"""{'solver': 'adam',
 'early_stopping': True,
 'random_state': 1907,
 'validation_fraction': 0.1,
 'n_iter_no_change': 7,
 'hidden_layer_sizes': (8, 6, 4),
 'activation': 'relu',
 'learning_rate_init': 0.001,
 'batch_size': 128,
 'max_iter': 400,
 'alpha': 0.01}
 
 Best Train MAE: 1851.9531
Best Val MAE:   1876.9947
Best Train R²:  0.8961
Best Val R²:    0.8918
"""

"{'solver': 'adam',\n 'early_stopping': True,\n 'random_state': 1907,\n 'validation_fraction': 0.1,\n 'n_iter_no_change': 7,\n 'hidden_layer_sizes': (8, 6, 4),\n 'activation': 'relu',\n 'learning_rate_init': 0.001,\n 'batch_size': 128,\n 'max_iter': 400,\n 'alpha': 0.01}\n\n Best Train MAE: 1851.9531\nBest Val MAE:   1876.9947\nBest Train R²:  0.8961\nBest Val R²:    0.8918\n"

In [48]:
best_params = results["best_params"]
best_params

{'solver': 'adam',
 'early_stopping': True,
 'random_state': 1907,
 'validation_fraction': 0.1,
 'n_iter_no_change': 7,
 'hidden_layer_sizes': (9, 5),
 'activation': 'relu',
 'learning_rate_init': 0.002,
 'batch_size': 256,
 'alpha': 0.01}

In [11]:
mlpr_params = {
    **{"random_state": RANDOM_SEED},
    **{"solver": "adam"}, 
    **{'early_stopping': True}, 
    **{'validation_fraction': 0.1}, 
    **{'n_iter_no_change': 7},
    **{'hidden_layer_sizes': (8, 4, 6)}, 
    **{'activation': 'relu'}, 
    **{'learning_rate_init': 0.003},
    **{"batch_size": 256}, 
    **{"alpha": 0.001}
}
scaler = MinMaxScaler()
ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
#mlpr_params = dict({"random_state": RANDOM_SEED},  **best_params)
mlpr_model=MLPRegressor
final_model, fitted_scaler, fitted_encoder, fill_values, train_feature_cols, freq_values, outlier_info = run_model(
    X, y, int_cols, float_cols, model_class=mlpr_model, model_params=mlpr_params, scaler=None, encoder=ohe,
    cat_cols=cat_cols,
    encoding_type="ohe")

In [55]:
test_df = pd.read_csv("test.csv")
test_copy = test_df.copy()
X_test = clean_df(test_copy, valid_models, cat_cols)
X_test = X_test.drop(columns=drop_cols)
XcarID=X_test.copy()

In [56]:
y_pred = predict_test(
    X_test,
    model=final_model,
    int_cols=int_cols,
    float_cols=float_cols,
    fill_values=fill_values,
    scaler=fitted_scaler,
    encoder=fitted_encoder,
    cat_cols=cat_cols,
    train_feature_cols=train_feature_cols,
    freq_values=freq_values,
    encoding_type="ohe",
    outlier_info=outlier_info
)

c:\Users\franc\Desktop\ml2526\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [57]:
submission = pd.DataFrame({
    "carID": XcarID.index,  
    "price": y_pred
})

# Check structure
display(submission.head())

# --- Save to CSV (with header, no index) ---
submission.to_csv("kaggle/model9.csv", index=False)

    carID         price
0   89856  13263.304459
1  106581  22364.666131
2   80886  14037.758481
3  100174  16148.215703
4   81376  21594.452947

In [ ]:
#se usarmos frequency encoding têm que levar scale tmb